import { z } from 'zod';
import { id, providerBaseUrl } from './common.js';
import { webhookCreate } from './management.js';

// ── GitHub App (0.13) ──────────────────────────────────────────────────────
// Request and response shapes for `/v1/github-apps/*` and
// `/v1/services/:id/github*`. Secrets (private key, webhook secret, client
// secret) only ever appear in REQUEST shapes; no response shape has a field
// that could carry one.

export const GITHUB_WEB_BASE_URL = 'https://github.com';
export const GITHUB_API_BASE_URL = 'https://api.github.com';

/** Mirrors `githubTokenScope` in `@ninedeploy/db`. */
export const githubTokenScope = z.enum(['repository', 'installation']);
export type GithubTokenScope = z.infer<typeof githubTokenScope>;

/** Mirrors `githubRepositorySelection` in `@ninedeploy/db`. */
export const githubRepositorySelection = z.enum(['all', 'selected']);

/**
 * A numeric GitHub id (App, installation, repository, account). GitHub ids
 * are positive and well below 2^53; `int()` keeps them safe integers.
 */
export const githubNumericId = z.number().int().positive();

/**
 * A GitHub user or organization login. It is interpolated into the manifest
 * `postUrl` path, so the character set is pinned to GitHub's own rule
 * (alphanumerics and single inner hyphens, at most 39 characters).
 */
export const githubLogin = z
  .string()
  .trim()
  .regex(/^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$/, 'invalid GitHub login');

/** `owner/repo`, as GitHub reports `full_name`. */
export const githubRepoFullName = z
  .string()
  .max(200)
  .regex(/^[A-Za-z0-9][A-Za-z0-9-]*\/[A-Za-z0-9._-]+$/, 'expected owner/repo');

/**
 * A PEM-encoded private key as GitHub hands it out (PKCS#1 `RSA PRIVATE KEY`)
 * or re-encoded as PKCS#8 (`PRIVATE KEY`). This is a shape check only; the
 * server proves the key by signing a JWT and calling `GET /app`.
 */
export const githubPrivateKeyPem = z
  .string()
  .trim()
  .max(16384)
  .regex(
    /^-----BEGIN (RSA )?PRIVATE KEY-----\r?\n[\s\S]+\r?\n-----END \1PRIVATE KEY-----$/,
    'privateKey must be a PEM private key (-----BEGIN RSA PRIVATE KEY-----)',
  );

const appName = z.string().trim().min(1).max(100);
const secretText = z.string().min(1).max(1024);
const clientId = z.string().trim().min(1).max(255);

const atLeastOneField = (value: Record<string, unknown>): boolean =>
  Object.values(value).some((v) => v !== undefined);

// ── Manifest flow ──────────────────────────────────────────────────────────

/**
 * POST /v1/github-apps/manifest. `org` is required for an organization-owned
 * App and refused for a personal one. `apiBaseUrl` may be omitted: the server
 * derives it (`https://api.github.com` for github.com, `<web>/api/v3` for
 * GitHub Enterprise Server).
 */
export const githubAppManifestRequest = z
  .object({
    target: z.enum(['user', 'org']),
    org: githubLogin.optional(),
    webBaseUrl: providerBaseUrl.default(GITHUB_WEB_BASE_URL),
    apiBaseUrl: providerBaseUrl.optional(),
    /** Also request `checks: write` (the Checks API itself is not used in 0.13). */
    checks: z.boolean().default(false),
  })
  .refine((v) => v.target !== 'org' || v.org !== undefined, {
    message: 'org is required when target is "org"',
    path: ['org'],
  })
  .refine((v) => v.target !== 'user' || v.org === undefined, {
    message: 'org is only valid when target is "org"',
    path: ['org'],
  });
export type GithubAppManifestRequest = z.input<typeof githubAppManifestRequest>;

/** The SPA submits `manifest` (JSON-encoded) as a form field to `postUrl`. */
export const githubAppManifestResponse = z.object({
  postUrl: z.string(),
  manifest: z.record(z.string(), z.unknown()),
  state: z.string(),
});
export type GithubAppManifestResponse = z.infer<typeof githubAppManifestResponse>;

/**
 * POST /v1/github-apps/manifest/complete. `code` is interpolated into
 * `/app-manifests/<code>/conversions`, so it is restricted to URL-path-safe
 * characters.
 */
export const githubAppManifestComplete = z.object({
  code: z
    .string()
    .min(1)
    .max(256)
    .regex(/^[A-Za-z0-9_-]+$/, 'invalid manifest code'),
  state: z.string().min(1).max(4096),
});
export type GithubAppManifestComplete = z.infer<typeof githubAppManifestComplete>;

// ── Manual entry (GHES or an existing App) ─────────────────────────────────

/**
 * POST /v1/github-apps. Omit both base URLs for github.com; for GitHub
 * Enterprise Server give both. Giving only one is refused, so a GHES App's JWT
 * is never sent to api.github.com by default. An omitted `webhookSecret` is
 * generated by the server and registered on the App.
 */
export const githubAppCreate = z
  .object({
    name: appName,
    appId: githubNumericId,
    privateKey: githubPrivateKeyPem,
    webhookSecret: secretText.optional(),
    clientId: clientId.optional(),
    clientSecret: secretText.optional(),
    webBaseUrl: providerBaseUrl.optional(),
    apiBaseUrl: providerBaseUrl.optional(),
  })
  .refine((v) => (v.webBaseUrl === undefined) === (v.apiBaseUrl === undefined), {
    message: 'webBaseUrl and apiBaseUrl go together; omit both for github.com',
    path: ['apiBaseUrl'],
  })
  .transform((v) => ({
    ...v,
    webBaseUrl: v.webBaseUrl ?? GITHUB_WEB_BASE_URL,
    apiBaseUrl: v.apiBaseUrl ?? GITHUB_API_BASE_URL,
  }));
export type GithubAppCreate = z.input<typeof githubAppCreate>;

/** PATCH /v1/github-apps/:id. `null` clears the optional OAuth client fields. */
export const githubAppPatch = z
  .object({
    name: appName.optional(),
    clientId: clientId.nullable().optional(),
    clientSecret: secretText.nullable().optional(),
  })
  .refine(atLeastOneField, { message: 'nothing to update' });
export type GithubAppPatch = z.infer<typeof githubAppPatch>;

/** PUT /v1/github-apps/:id/private-key. */
export const githubAppPrivateKey = z.object({ privateKey: githubPrivateKeyPem });
export type GithubAppPrivateKey = z.infer<typeof githubAppPrivateKey>;

// ── Views (responses: metadata only, never a secret) ───────────────────────

export const githubApp = z.object({
  id: z.number().int(),
  name: z.string(),
  appId: z.number().int(),
  slug: z.string().nullable(),
  clientId: z.string().nullable(),
  ownerLogin: z.string().nullable(),
  ownerType: z.string().nullable(),
  webBaseUrl: z.string(),
  apiBaseUrl: z.string(),
  htmlUrl: z.string().nullable(),
  permissions: z.record(z.string(), z.string()).nullable(),
  events: z.array(z.string()).nullable(),
  /** Where GitHub delivers this App's webhooks (`/v1/hooks/github-app/<key>`). */
  webhookUrl: z.string(),
  /** `${htmlUrl}/installations/new`; null until the App's html URL is known. */
  installUrl: z.string().nullable(),
  hasPrivateKey: z.boolean(),
  hasClientSecret: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type GithubApp = z.infer<typeof githubApp>;

export const githubAppInstallation = z.object({
  id: z.number().int(),
  githubAppId: z.number().int(),
  installationId: z.number().int(),
  accountLogin: z.string().nullable(),
  accountType: z.string().nullable(),
  accountId: z.number().int().nullable(),
  repositorySelection: githubRepositorySelection,
  permissions: z.record(z.string(), z.string()).nullable(),
  /** The generated `github_app` source; null once that source was deleted. */
  sourceId: z.number().int().nullable(),
  suspendedAt: z.string().nullable(),
  removedAt: z.string().nullable(),
  /** GitHub's settings page for this installation. */
  configureUrl: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type GithubAppInstallation = z.infer<typeof githubAppInstallation>;

// ── Service ↔ repository link ──────────────────────────────────────────────

const linkWatchPaths = webhookCreate.shape.watchPaths.unwrap();

/**
 * PUT /v1/services/:id/github (operator). `sourceId` is a `github_app` source
 * and so names the installation. `repoId` may be omitted; the server then
 * resolves it from the service's repository URL. `tokenScope` widens clone
 * tokens to the whole installation (sibling-repo submodules), so it lives on
 * this operator route and not on the admin feedback PATCH.
 */
export const serviceGithubLinkPut = z.object({
  sourceId: id,
  repoId: githubNumericId.optional(),
  tokenScope: githubTokenScope.optional(),
  /** Newline/comma-separated globs (same rules as a webhook); null clears. */
  watchPaths: linkWatchPaths.nullable().optional(),
  enabled: z.boolean().optional(),
});
export type ServiceGithubLinkPut = z.infer<typeof serviceGithubLinkPut>;

/** PATCH /v1/services/:id/github/feedback (admin). Both default to off. */
export const serviceGithubFeedbackPatch = z
  .object({
    /** Post commit statuses (`ninedeploy/<slug>`) for deploys. */
    reportStatus: z.boolean().optional(),
    /** Upsert one comment per PR with the preview URL and outcome. */
    prComment: z.boolean().optional(),
  })
  .refine(atLeastOneField, { message: 'nothing to update' });
export type ServiceGithubFeedbackPatch = z.infer<typeof serviceGithubFeedbackPatch>;

/**
 * POST /v1/services/:id/github/migrate (operator). Links the service to the
 * App installation behind `sourceId`, remembering the current source as
 * `previousSourceId`; the service's own source and webhook are left as is.
 */
export const serviceGithubMigrate = z.object({ sourceId: id });
export type ServiceGithubMigrate = z.infer<typeof serviceGithubMigrate>;

/** GET /v1/services/:id/github → `{ link }`, `link` null when unlinked. */
export const serviceGithubLink = z.object({
  id: z.number().int(),
  serviceId: z.number().int(),
  installationRowId: z.number().int(),
  githubAppId: z.number().int(),
  /** The installation's `github_app` source, when it still exists. */
  sourceId: z.number().int().nullable(),
  repoId: z.number().int(),
  repoFullName: z.string(),
  enabled: z.boolean(),
  tokenScope: githubTokenScope,
  watchPaths: z.string().nullable(),
  reportStatus: z.boolean(),
  prComment: z.boolean(),
  previousSourceId: z.number().int().nullable(),
  /** Enabled AND the installation is neither suspended nor removed: the App drives deploys. */
  active: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type ServiceGithubLink = z.infer<typeof serviceGithubLink>;

export const serviceGithubStatus = z.object({ link: serviceGithubLink.nullable() });
export type ServiceGithubStatus = z.infer<typeof serviceGithubStatus>;
