import yaml from 'js-yaml';
import { ninedeployManifest, type NinedeployManifest } from '@ninedeploy/schemas';

/**
 * Parse a raw `.ninedeploy` YAML string into a typed object.
 *
 * This is the SDK-level counterpart of the server's loader (`@ninedeploy/server`
 * `ninedeployManifest.ts`): it does the same YAML → Zod step but skips the
 * filesystem and secret-scan concerns that only matter at deploy time. The
 * CLI and any external tool that wants to validate a manifest without
 * calling the server go through here.
 *
 * Throws a `ManifestParseError` for malformed YAML and a
 * `ManifestValidationError` when the parsed document fails the schema.
 */
export class ManifestParseError extends Error {
  constructor(
    public readonly source: string,
    public override readonly cause: unknown,
  ) {
    const reason = cause instanceof Error ? cause.message : String(cause);
    super(`.ninedeploy parse error: ${reason}`);
    this.name = 'ManifestParseError';
  }
}

export class ManifestValidationError extends Error {
  constructor(
    public readonly issues: ReadonlyArray<{ path: string; message: string }>,
  ) {
    const detail = issues.map((i) => `  - ${i.path || '<root>'}: ${i.message}`).join('\n');
    super(`.ninedeploy validation failed:\n${detail}`);
    this.name = 'ManifestValidationError';
  }
}

export function parseManifestYaml(yamlText: string): NinedeployManifest {
  let doc: unknown;
  try {
    doc = yaml.load(yamlText);
  } catch (err) {
    throw new ManifestParseError('<string>', err);
  }
  if (doc == null) {
    throw new ManifestValidationError([{ path: '', message: 'manifest is empty' }]);
  }
  const result = ninedeployManifest.safeParse(doc);
  if (!result.success) {
    throw new ManifestValidationError(
      result.error.issues.map((i) => ({ path: i.path.join('.'), message: i.message })),
    );
  }
  return result.data;
}

/**
 * Format a manifest as YAML for round-tripping (download a manifest the
 * server parsed, or write one to a fresh repo). Produces a header comment
 * explaining the file and uses block style for nested objects.
 */
export function formatManifestYaml(manifest: NinedeployManifest): string {
  // Hand-rolled YAML emission: the manifest is small and stable enough that
  // depending on a second pass through `yaml.load` would be a waste. Block
  // style throughout so the file is human-editable.
  const lines: string[] = [
    '# .ninedeploy — NineDeploy project manifest.',
    '# Committed to the repo. Secrets NEVER go in this file — use the panel env vault.',
    `# Generated by @ninedeploy/sdk on ${new Date().toISOString()}.`,
    'version: "1"',
  ];

  if (manifest.runtime) {
    lines.push('runtime:');
    lines.push(`  type: ${manifest.runtime.type}`);
    if (manifest.runtime.version) lines.push(`  version: "${manifest.runtime.version}"`);
  }

  if (manifest.build) {
    lines.push('build:');
    if (manifest.build.install) lines.push(`  install: ${quote(manifest.build.install)}`);
    if (manifest.build.build) lines.push(`  build: ${quote(manifest.build.build)}`);
    if (manifest.build.start) lines.push(`  start: ${quote(manifest.build.start)}`);
    if (manifest.build.baseDir) lines.push(`  baseDir: ${quote(manifest.build.baseDir)}`);
    if (manifest.build.dockerfile) lines.push(`  dockerfile: ${quote(manifest.build.dockerfile)}`);
  }

  if (manifest.run) {
    lines.push('run:');
    if (manifest.run.port != null) lines.push(`  port: ${manifest.run.port}`);
    if (manifest.run.healthcheck) lines.push(`  healthcheck: ${quote(manifest.run.healthcheck)}`);
    if (manifest.run.restart) lines.push(`  restart: ${quote(manifest.run.restart)}`);
  }

  if (manifest.static) {
    lines.push('static:');
    lines.push(`  spa: ${manifest.static.spa}`);
    if (manifest.static.root) lines.push(`  root: ${quote(manifest.static.root)}`);
  }

  if (manifest.env) {
    lines.push('env:');
    if (manifest.env.required.length > 0) {
      lines.push('  required:');
      for (const k of manifest.env.required) lines.push(`    - ${k}`);
    }
    if (manifest.env.aliases) {
      lines.push('  aliases:');
      for (const [from, to] of Object.entries(manifest.env.aliases)) {
        lines.push(`    ${from}: ${to}`);
      }
    }
  }

  if (manifest.phases) {
    lines.push('phases:');
    if (manifest.phases.setup?.pkgs?.length) {
      lines.push('  setup:');
      lines.push('    pkgs:');
      for (const p of manifest.phases.setup.pkgs) lines.push(`      - ${p}`);
    }
    if (manifest.phases.build?.cmds?.length) {
      lines.push('  build:');
      lines.push('    cmds:');
      for (const c of manifest.phases.build.cmds) lines.push(`      - ${quote(c)}`);
    }
  }

  if (manifest.resources) {
    lines.push('resources:');
    if (manifest.resources.cpuShares != null) lines.push(`  cpuShares: ${manifest.resources.cpuShares}`);
    if (manifest.resources.memMb != null) lines.push(`  memMb: ${manifest.resources.memMb}`);
  }

  if (manifest.hooks) {
    lines.push('hooks:');
    if (manifest.hooks.preBuild) lines.push(`  preBuild: ${quote(manifest.hooks.preBuild)}`);
    if (manifest.hooks.postBuild) lines.push(`  postBuild: ${quote(manifest.hooks.postBuild)}`);
    if (manifest.hooks.preStop) lines.push(`  preStop: ${quote(manifest.hooks.preStop)}`);
  }

  if (manifest.watch) {
    lines.push('watch:');
    lines.push('  paths:');
    for (const p of manifest.watch.paths) lines.push(`    - ${quote(p)}`);
  }

  if (manifest.routes) {
    lines.push('routes:');
    for (const r of manifest.routes) {
      lines.push(`  - host: ${r.host}`);
      lines.push(`    path: ${quote(r.path)}`);
      lines.push(`    ssl: ${r.ssl}`);
      if (r.redirectWww) lines.push(`    redirectWww: ${r.redirectWww}`);
      if (r.headers) {
        lines.push('    headers:');
        for (const [k, v] of Object.entries(r.headers)) lines.push(`      ${k}: ${quote(v)}`);
      }
      if (r.ipAllowlist) {
        lines.push('    ipAllowlist:');
        for (const cidr of r.ipAllowlist) lines.push(`      - ${cidr}`);
      }
      if (r.rateLimit) {
        lines.push('    rateLimit:');
        lines.push(`      average: ${r.rateLimit.average}`);
        lines.push(`      burst: ${r.rateLimit.burst}`);
      }
    }
  }

  if (manifest.previews) {
    lines.push('previews:');
    lines.push(`  enabled: ${manifest.previews.enabled}`);
    if (manifest.previews.pattern) lines.push(`  pattern: ${quote(manifest.previews.pattern)}`);
    lines.push(`  maxActive: ${manifest.previews.maxActive}`);
    lines.push(`  autoDestroyOnClose: ${manifest.previews.autoDestroyOnClose}`);
  }

  if (manifest.volume) {
    lines.push('volume:');
    if (manifest.volume.mount != null) lines.push(`  mount: ${quote(manifest.volume.mount)}`);
    if (manifest.volume.backups) {
      lines.push('  backups:');
      lines.push(`    schedule: ${quote(manifest.volume.backups.schedule)}`);
      lines.push(`    retention: ${manifest.volume.backups.retention}`);
    }
  }

  if (manifest.database) {
    lines.push('database:');
    lines.push(`  ref: ${manifest.database.ref}`);
    lines.push(`  env: ${manifest.database.env}`);
  }

  if (manifest.network) {
    lines.push('network:');
    if (manifest.network.publishPort != null) lines.push(`  publishPort: ${manifest.network.publishPort}`);
    if (manifest.network.aliases.length > 0) {
      lines.push('  aliases:');
      for (const a of manifest.network.aliases) lines.push(`    - ${a}`);
    }
  }

  if (manifest.notifications) {
    lines.push('notifications:');
    if (manifest.notifications.onDeploy.length > 0) {
      lines.push('  onDeploy:');
      for (const c of manifest.notifications.onDeploy) lines.push(`    - ${c}`);
    }
    if (manifest.notifications.onFailure.length > 0) {
      lines.push('  onFailure:');
      for (const c of manifest.notifications.onFailure) lines.push(`    - ${c}`);
    }
    if (manifest.notifications.onAlert.length > 0) {
      lines.push('  onAlert:');
      for (const c of manifest.notifications.onAlert) lines.push(`    - ${c}`);
    }
  }

  if (manifest.alerts) {
    lines.push('alerts:');
    for (const a of manifest.alerts) {
      lines.push(`  - when: ${a.when}`);
      lines.push(`    channel: ${a.channel}`);
      if (a.thresholdPct != null) lines.push(`    thresholdPct: ${a.thresholdPct}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function quote(value: string): string {
  // Single-line strings without shell-special chars stay unquoted. Anything
  // containing a colon, hash, bracket, quote, or backslash gets wrapped in
  // double quotes with internal double-quote escaping.
  if (/^[A-Za-z0-9._/-]+$/.test(value)) return value;
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

// ── Project-type detection for `init` ────────────────────────────────────

export type ProjectKind = 'node-npm' | 'node-pnpm' | 'python' | 'go' | 'static' | 'unknown';

const PROJECT_MARKERS: ReadonlyArray<{ kind: ProjectKind; files: ReadonlyArray<string> }> = [
  { kind: 'node-pnpm', files: ['pnpm-lock.yaml', 'pnpm-workspace.yaml'] },
  { kind: 'python', files: ['pyproject.toml', 'requirements.txt', 'Pipfile'] },
  { kind: 'go', files: ['go.mod'] },
  { kind: 'static', files: ['vite.config.ts', 'vite.config.js', 'index.html'] },
  { kind: 'node-npm', files: ['package.json'] },
];

/**
 * Pick a starter-template kind from a list of files present in the repo
 * root. The first match wins. Order in `PROJECT_MARKERS` is the precedence:
 * pnpm is more specific than the generic `package.json`; `static` is for
 * Vite/static frontends without a build server.
 */
export function detectProjectKind(files: ReadonlyArray<string>): ProjectKind {
  for (const marker of PROJECT_MARKERS) {
    if (marker.files.some((f) => files.includes(f))) return marker.kind;
  }
  return 'unknown';
}

/**
 * Produce a starter `.ninedeploy` for a given project kind. The result is
 * opinionated: it pins Node 20 (current LTS), uses the manifest to declare
 * a domain placeholder, and sets sensible defaults. The operator is
 * expected to edit the file before committing.
 */
export function starterManifest(kind: ProjectKind): NinedeployManifest {
  switch (kind) {
    case 'node-npm':
      return {
        version: '1',
        runtime: { type: 'node', version: '20' },
        build: { install: 'npm ci', build: 'npm run build', start: 'npm start' },
        run: { port: 3000, restart: 'unless-stopped' },
        routes: [{ host: 'app.example.com', path: '/', ssl: true }],
      };
    case 'node-pnpm':
      return {
        version: '1',
        runtime: { type: 'node', version: '20' },
        build: { install: 'pnpm install --frozen-lockfile', build: 'pnpm build', start: 'pnpm start' },
        run: { port: 3000, restart: 'unless-stopped' },
      };
    case 'python':
      return {
        version: '1',
        runtime: { type: 'python', version: '3.12' },
        build: { install: 'pip install -r requirements.txt', start: 'python main.py' },
        run: { port: 8000, restart: 'unless-stopped' },
      };
    case 'go':
      return {
        version: '1',
        runtime: { type: 'go', version: '1.22' },
        build: { build: 'go build -o app .', start: './app' },
        run: { port: 8080, restart: 'unless-stopped' },
      };
    case 'static':
      return {
        version: '1',
        static: { spa: true, root: 'dist' },
        build: { install: 'npm ci', build: 'npm run build' },
        run: { port: 3000, restart: 'unless-stopped' },
      };
    case 'unknown':
      return {
        version: '1',
        runtime: { type: 'auto' },
        run: { port: 3000, restart: 'unless-stopped' },
      };
  }
}
