import { createHmac, randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { agentChildTimeoutMs } from '../lib/agentClient.js';
import { spawnValidated } from '../lib/spawnValidated.js';
import type { AgentOpModule } from './index.js';
import { type Params, RE_NAME, RE_PATH, RE_SERVICE_IMAGE_TAG, str, validated } from './operands.js';

/**
 * Source builds on a node (multi-node, design §2): `build.nixpacks` and
 * `build.railpack`, the capabilities of the same names. The agent runs the
 * panel's image, which already ships the checksum-pinned Nixpacks and Railpack
 * CLIs and buildx (Dockerfile), so a node only lacked the ops.
 *
 * The panel decides WHAT to build (pack resolution happens on the panel's own
 * checkout, engine/builders/remoteDocker.ts); these ops only build it. Every
 * operand is validated, every repository path is symlink-walked under the
 * service workspace, and the argv is built here from literal flags — nothing
 * in a request is ever passed through as a flag.
 *
 * Build env: the service's environment reaches a build (NEXT_PUBLIC_* inlining,
 * NIXPACKS_* pins). A request carrying any is accepted only SEALED.
 *   - Nixpacks has no env-file option: values travel as `--env K=V` on its
 *     argv, which is exactly the panel host's exposure today (`nixpacksEnvArgs`).
 *   - Railpack runs through the node daemon's BuildKit with Railpack's
 *     frontend: values are BuildKit secrets read from the child's environment,
 *     never argv. Only `RAILPACK_*` build-configuration variables keep their
 *     value on the `railpack prepare` argv (they shape the plan, like the
 *     install/build commands Nixpacks takes as flags).
 * Every value longer than 3 characters is redacted from the lines returned.
 */

/** Must equal engine/builders/docker.ts `GENERATED_NIXPACKS_MARKER` (pinned by a test; the agent does not import the builder). */
export const NIXPACKS_TOML_MARKER =
  '# Generated by NineDeploy from .ninedeploy runtime/phases on every deploy — commit your own nixpacks.toml to take over.';

/** The bundled Railpack CLI (Dockerfile `ARG RAILPACK_VERSION`, pinned by a test). */
export const RAILPACK_VERSION = '0.39.0';
/** Railpack's BuildKit frontend, pinned to the bundled CLI so the plan format always matches. */
export const RAILPACK_FRONTEND_IMAGE = `ghcr.io/railwayapp/railpack-frontend:v${RAILPACK_VERSION}`;

const MAX_ENV_KEYS = 512;
const MAX_ENV_VALUE = 32 * 1024;
const MAX_TOML = 64 * 1024;
const MAX_CMD = 4096;
const MAX_TAG = 255;
const RE_ENV_KEY = /^[A-Za-z_][A-Za-z0-9_]{0,255}$/;
/** The Railpack scratch directory in the workspace (plan and info files). */
export const RAILPACK_WORK_DIR = '.nd-railpack';

/** The validated build env (empty when absent). */
export function buildEnvOperand(raw: unknown): Record<string, string> {
  if (raw === undefined) return {};
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw) || Object.getPrototypeOf(raw) !== Object.prototype) {
    throw new Error('Invalid build env');
  }
  const entries = Object.entries(raw as Record<string, unknown>);
  if (entries.length > MAX_ENV_KEYS) throw new Error(`Invalid build env: more than ${MAX_ENV_KEYS} variables`);
  const env: Record<string, string> = {};
  for (const [key, value] of entries) {
    if (!RE_ENV_KEY.test(key)) throw new Error(`Invalid build env name ${key.slice(0, 64)}`);
    if (typeof value !== 'string' || value.length > MAX_ENV_VALUE || value.includes('\0')) throw new Error(`Invalid build env value for ${key}`);
    env[key] = value;
  }
  return env;
}

/** Sealed only when the request carries build env (an unparseable `env` is treated as carrying some). */
export function buildCarriesEnv(params: Params): boolean {
  const raw = params['env'];
  if (raw === undefined) return false;
  return !(typeof raw === 'object' && raw !== null && !Array.isArray(raw) && Object.keys(raw).length === 0);
}

/** Nixpacks' argv convention for a value (the panel host's `nixpacksEnvArgs`): physical newlines become `\n`. */
const nixpacksValue = (value: string): string => value.replace(/\r\n?|\n/g, '\\n');

/** Redact every env value (and its escaped form) longer than 3 characters from a line. */
export function envRedactor(env: Record<string, string>): (line: string) => string {
  const secrets = [
    ...new Set(
      Object.values(env)
        .flatMap((v) => [v, nixpacksValue(v), ...v.split(/\r\n?|\n/)])
        .filter((v) => v.length > 3),
    ),
  ].sort((a, b) => b.length - a.length);
  if (secrets.length === 0) return (line) => line;
  return (line) => {
    let out = line;
    for (const secret of secrets) out = out.split(secret).join('[redacted]');
    return out;
  };
}

/** The service workspace and the symlink-walked base directory a build names. */
async function buildWorkspace(params: Params): Promise<{
  dir: string;
  baseDir: string;
  assertPath: (base: string, value: string, what: string) => string;
}> {
  // agent.ts imports this module through the registry: load it at call time.
  const { resolveWorkspace, assertPathInWorkspace } = await import('../agent.js');
  const dir = await resolveWorkspace(validated(str(params, 'workspace'), RE_NAME, 'workspace name'));
  const baseDir = validated(str(params, 'baseDir') ?? '.', RE_PATH, 'base directory').replace(/\/+$/, '') || '.';
  assertPathInWorkspace(dir, baseDir, 'base directory');
  return { dir, baseDir, assertPath: assertPathInWorkspace };
}

function tagOperand(params: Params): string {
  const tag = validated(str(params, 'tag'), RE_SERVICE_IMAGE_TAG, 'image tag (ninedeploy/<slug>:<tag>)');
  if (tag.length > MAX_TAG) throw new Error('Invalid image tag');
  return tag;
}

/** An optional install/build/start command for Nixpacks, as one `--flag=value` element (never a separate, flag-like token). */
function commandFlag(params: Params, key: string, flag: string): string[] {
  const raw = params[key];
  if (raw === undefined || raw === null || raw === '') return [];
  if (typeof raw !== 'string' || raw.length > MAX_CMD || raw.includes('\0')) throw new Error(`Invalid ${key}`);
  return [`${flag}=${raw}`];
}

/**
 * The panel-generated `nixpacks.toml` (r274 rules, as the panel host's
 * `buildWithNixpacks`): a repository-committed file wins; our own (marker
 * first line) is replaced; with no manifest a stale one of ours is removed.
 */
function syncNixpacksToml(
  dir: string,
  baseDir: string,
  toml: string | undefined,
  assertPath: (base: string, value: string, what: string) => string,
  onLine: (line: string) => void,
): void {
  const rel = baseDir === '.' ? 'nixpacks.toml' : `${baseDir}/nixpacks.toml`;
  assertPath(dir, rel, 'nixpacks.toml');
  const file = join(dir, rel);
  const existing = existsSync(file) ? readFileSync(file, 'utf8') : null;
  const ours = existing !== null && existing.startsWith(NIXPACKS_TOML_MARKER);
  if (toml !== undefined) {
    if (existing !== null && !ours) {
      onLine('📋 .ninedeploy: repo already ships a nixpacks.toml — keeping it, manifest runtime/phases ignored');
      return;
    }
    writeFileSync(file, toml, { encoding: 'utf8', mode: 0o644 });
    onLine(`📋 .ninedeploy: generated nixpacks.toml from runtime/phases (${toml.split('\n').length - 1} lines)`);
  } else if (ours) {
    rmSync(file, { force: true });
    onLine('📋 .ninedeploy: removed the nixpacks.toml generated by an earlier deploy');
  }
}

function tomlOperand(raw: unknown): string | undefined {
  if (raw === undefined || raw === null) return undefined;
  if (typeof raw !== 'string' || raw.length > MAX_TOML || raw.includes('\0') || !raw.startsWith(`${NIXPACKS_TOML_MARKER}\n`)) {
    throw new Error('Invalid nixpacksToml: it must be the panel-generated file');
  }
  return raw;
}

/**
 * `build.nixpacks {workspace, baseDir, tag, installCmd?, buildCmd?, startCmd?, env?, nixpacksToml?}`:
 * `nixpacks build <baseDir> --name <tag> [--install-cmd=…] [--build-cmd=…] [--start-cmd=…] [--env K=V …]`
 * in the service workspace, with the build budget.
 */
export async function nixpacksBuildOp(params: Params, onLine: (line: string) => void): Promise<number> {
  const { dir, baseDir, assertPath } = await buildWorkspace(params);
  const tag = tagOperand(params);
  const env = buildEnvOperand(params['env']);
  const toml = tomlOperand(params['nixpacksToml']);
  const custom = [
    ...commandFlag(params, 'installCmd', '--install-cmd'),
    ...commandFlag(params, 'buildCmd', '--build-cmd'),
    ...commandFlag(params, 'startCmd', '--start-cmd'),
  ];
  const redact = envRedactor(env);
  const out = (line: string) => onLine(redact(line));
  syncNixpacksToml(dir, baseDir, toml, assertPath, out);
  const envArgs = Object.entries(env).flatMap(([k, v]) => ['--env', `${k}=${nixpacksValue(v)}`]);
  if (envArgs.length > 0) out(`Injecting ${envArgs.length / 2} environment variable(s) into the Nixpacks build (values are never logged)`);
  out(`⚡ nixpacks build on the node: ${baseDir} …`);
  return spawnValidated('nixpacks', ['build', baseDir, '--name', tag, ...custom, ...envArgs], out, {
    cwd: dir,
    timeoutMs: agentChildTimeoutMs('build.nixpacks') as number,
  });
}

/** Per-process key for the Railpack `secrets-hash` (cache busting without putting a plain hash of the values on argv). */
const SECRETS_HASH_KEY = randomBytes(32);

/** `NINEDEPLOY_AGENT_BUILDKIT_HOST`: the node owner's own BuildKit for `railpack build` (empty = the frontend path). */
const RE_BUILDKIT_HOST = /^(?:tcp|unix|docker-container|kube-pod|podman-container|nerdctl-container):\/\/[A-Za-z0-9@:/._=-]+$/;
export function agentBuildkitHost(env: NodeJS.ProcessEnv = process.env): string | null {
  const raw = (env['NINEDEPLOY_AGENT_BUILDKIT_HOST'] ?? '').trim();
  if (raw === '') return null;
  if (!RE_BUILDKIT_HOST.test(raw)) throw new Error('NINEDEPLOY_AGENT_BUILDKIT_HOST on this node is not a BuildKit address');
  return raw;
}

/** Railpack's own build-configuration variables keep their value at plan time. */
const isRailpackConfig = (key: string): boolean => key.startsWith('RAILPACK_');

/**
 * `build.railpack {workspace, baseDir, tag, env?}`. Without
 * `NINEDEPLOY_AGENT_BUILDKIT_HOST` (the default) it uses the node daemon's
 * built-in BuildKit through Railpack's frontend:
 *   1. `railpack prepare <baseDir> --plan-out .nd-railpack/plan.json --info-out .nd-railpack/info.json [--env K=…]`
 *   2. `docker buildx build --load -t <tag> --build-arg BUILDKIT_SYNTAX=<frontend> -f .nd-railpack/plan.json
 *       [--secret id=K,env=ND_RAILPACK_SECRET_n …] <baseDir>`, the values in the child's environment only.
 * With it set, `railpack build <baseDir> --name <tag> [--env K=V …]` against that daemon (the panel host's form).
 */
export async function railpackBuildOp(params: Params, onLine: (line: string) => void, env: NodeJS.ProcessEnv = process.env): Promise<number> {
  const { dir, baseDir, assertPath } = await buildWorkspace(params);
  const tag = tagOperand(params);
  const vars = buildEnvOperand(params['env']);
  const redact = envRedactor(vars);
  const out = (line: string) => onLine(redact(line));
  const timeoutMs = agentChildTimeoutMs('build.railpack') as number;
  const buildkit = agentBuildkitHost(env);
  if (buildkit !== null) {
    out(`⚡ railpack build on the node (BuildKit at NINEDEPLOY_AGENT_BUILDKIT_HOST): ${baseDir} …`);
    const envArgs = Object.entries(vars).flatMap(([k, v]) => ['--env', `${k}=${v}`]);
    return spawnValidated('railpack', ['build', baseDir, '--name', tag, ...envArgs], out, {
      cwd: dir,
      timeoutMs,
      env: { BUILDKIT_HOST: buildkit },
    });
  }

  assertPath(dir, `${RAILPACK_WORK_DIR}/plan.json`, 'railpack plan');
  const work = join(dir, RAILPACK_WORK_DIR);
  // Our namespace: whatever a repository put there (a symlink included) is removed, never followed.
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { mode: 0o700 });
  const keys = Object.keys(vars).sort();
  try {
    const prepareArgs = [
      'prepare',
      baseDir,
      '--plan-out',
      `${RAILPACK_WORK_DIR}/plan.json`,
      '--info-out',
      `${RAILPACK_WORK_DIR}/info.json`,
      // The plan names every variable (so the frontend mounts it as a
      // secret); only Railpack's own configuration carries its value here.
      ...keys.flatMap((k) => ['--env', isRailpackConfig(k) ? `${k}=${vars[k]}` : `${k}=`]),
    ];
    out(`⚡ railpack prepare on the node: ${baseDir} …`);
    const prepared = await spawnValidated('railpack', prepareArgs, out, { cwd: dir });
    if (prepared !== 0) return prepared;

    const secretEnv: Record<string, string> = {};
    const secretArgs: string[] = [];
    keys.forEach((k, i) => {
      // A separate variable name per secret: a service variable called PATH
      // or DOCKER_HOST must never become the docker CLI's own environment.
      const envName = `ND_RAILPACK_SECRET_${i}`;
      secretEnv[envName] = vars[k] as string;
      secretArgs.push('--secret', `id=${k},env=${envName}`);
    });
    const hash = createHmac('sha256', SECRETS_HASH_KEY)
      .update(keys.map((k) => `${k}=${vars[k]}`).join('\n'))
      .digest('hex');
    const buildArgs = [
      'buildx',
      'build',
      '--load',
      '--progress',
      'plain',
      '-t',
      tag,
      '--build-arg',
      `BUILDKIT_SYNTAX=${RAILPACK_FRONTEND_IMAGE}`,
      '--build-arg',
      `secrets-hash=${hash}`,
      '-f',
      `${RAILPACK_WORK_DIR}/plan.json`,
      ...secretArgs,
      baseDir,
    ];
    if (keys.length > 0) out(`Passing ${keys.length} environment variable(s) to the Railpack build as BuildKit secrets (values are never logged)`);
    out(`⚡ docker buildx build with the Railpack frontend (${RAILPACK_FRONTEND_IMAGE}) …`);
    return await spawnValidated('docker', buildArgs, out, { cwd: dir, timeoutMs, env: secretEnv });
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

export const buildOps: AgentOpModule = {
  name: 'agentOps/builds.ts',
  caps: ['build.nixpacks', 'build.railpack'],
  ops: {
    'build.nixpacks': { cap: 'build.nixpacks', sealedOnly: buildCarriesEnv, run: (p, onLine) => nixpacksBuildOp(p, onLine) },
    'build.railpack': { cap: 'build.railpack', sealedOnly: buildCarriesEnv, run: (p, onLine) => railpackBuildOp(p, onLine) },
  },
};
