export const VERSION = '0.7.3';

export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '0.7.3',
    date: '2026-09-06',
    title: 'Two Quiet Reliability Fixes Caught by 0.7.1 Going Out',
    changes: [
      'The `git://` protocol is now part of the egress SSRF guard. `lib/gitEgress.ts` handled only `http://`, `https://`, and `ssh://` URLs, leaving `git://` (port 9418, supported by `simple-git`) with no check — a repository URL of `git://169.254.169.254/...` could reach the cloud metadata service and leak instance credentials, and `git://<private-LAN>/...` could reach internal Git servers. The `git://` branch parses the URL and calls `rejectIfPrivateHost`, mirroring the `ssh://` guard; four new regression cases cover the metadata service, RFC1918 LAN, loopback, and the positive public case',
      'The Traefik bridge reaper actually reaps. Docker\'s `--filter name=<value>` is a substring match, not a regex, so the `^` anchors in `name=^nd-svc-` and `name=^ndcmp-` were treated as literal characters and the filter matched no bridge — after any Traefik restart (deploy, host reboot, image update) the reaper silently returned zero bridges and Traefik was never re-attached to the per-slug `nd-svc-<slug>` meshes or the `ndcmp-<slug>_default` compose defaults, so every domain on those meshes answered 502 until a full service redeploy ran `ensureServiceBridge` for that slug. The anchors are gone and a regression test pins the substring-not-regex invariant so it cannot silently regress',
    ],
  },
  {
    version: '0.7.1',
    date: '2026-09-05',
    title: 'Three Quiet Reliability Fixes Caught by 0.7.0 Going Out',
    changes: [
      'Remote compose stop() stops tearing down the wrong project. The previous recovery stripped a single trailing `-[^-]+-\\d+` block from `<project>-<service>-1` to reach the project — but the compose service key is a user-controlled YAML map name and can contain hyphens itself (`services.frontend-api:`), so `ndcmp-web-frontend-api-1` extracted `ndcmp-web-frontend` instead of `ndcmp-web`. The production path then ran `docker compose down -p ndcmp-web-frontend` on the node, tearing down whatever stack happened to share that name. The builder now records the project it minted for each runtimeId at buildAndRun time and looks it up at stop(): no string surgery, a runtimeId this builder never recorded is refused outright rather than guessed, and a redeploy of the same service overwrites its own mapping (Map, not array — the latest project wins)',
      '`createDb({ withClient: false })` actually suppresses the raw libSQL client. The option was a dead no-op since the field existed: the raw client was always returned, so read-only workers that wanted to release the underlying connection (the runtime migrator is one) could not. The Drizzle handle is unaffected; the client is omitted only when the caller asks, and the regression test pins both the suppression and that the Drizzle handle still answers queries',
      'The database-URL secret pattern now matches percent-encoded passwords. A literal `@` cannot appear in the password class (it is the user/host delimiter) but its URL-encoded form `%40` can, and tools that build connection strings from user input routinely emit `%40` instead of escaping it themselves. The old regex treated the entire non-special class as raw, so a connection string with `%40` in the password was never caught by the secret scanner and slipped into env vars and the panel as a "no credentials detected" string. The pattern now accepts `[non-special] | %XX` triplets in the password class, the `{3,}` minimum still measures raw characters (so a real password still satisfies the guardrail), and the secret scanner covers what connection-string builders actually produce',
    ],
  },
  {
    version: '0.7.0',
    date: '2026-09-04',
    title: 'Multi-Node Deployments With Per-Node Ingress, Settings That Actually Do Something & an Honest Feature List',
    changes: [
      'Multi-node deployments work. `server_id` had been on the services table, on the Servers page and in the build context since the fleet feature shipped, and NO builder read it — every builder shells out locally, so a service pinned to a node would have been built and started on the panel host while the panel, the Servers page and the deploy log all reported the node. It was refused outright rather than deployed to the wrong machine. A docker service pinned to a node is now built and started ON that node through the typed agent protocol: the repository is checked out in a per-service workspace, the image is built or pulled there, and the environment arrives as a 0600 env-file that is deleted the moment the container has taken it',
      'Compose stacks run on a node too, which is what makes the one-click template catalogue usable there at all — most of it is compose-shaped, so multi-node previously covered hand-rolled docker services and nothing else. The panel ships an inline stack YAML (or the node checks the repository out), writes the .env and any volume-attachment override, then runs the same ordering the local builder uses: `compose config` and `compose pull` complete while the PREVIOUS revision is still serving, so a broken interpolation or a bad tag fails the deployment without ever tearing the live stack down. The platform restart policy is applied afterwards, because a compose file with no `restart:` leaves every container dead after a reboot and nobody is watching a remote node',
      'Each node runs its own Traefik, so you point the domain at the NODE and production traffic never hairpins through the panel — the model that makes multi-node worth having. The panel stays the source of truth for domains, middlewares and certificates: it renders both Traefik configs with the same functions that generate its own and ships them to the node, which only writes them to a fixed path. Any routing change refreshes every node automatically, and the node proxy is recreated only when the STATIC config changed, so a domain edit is not an ingress interruption',
      'The panel proxy and each node proxy now render only THEIR OWN services. A router upstream is a container name resolved over the local Docker network, so once nodes really ran containers, rendering every service into every proxy would have made the panel advertise routes for containers on another machine and answer 502 for each one — with the node doing the same in reverse. A node also never receives the panel dashboard router, which would otherwise blackhole the control plane behind whichever node answered DNS first',
      'Node agents gained per-service workspaces. Git has no per-invocation repository operand — fetch, checkout and reset act on the process working directory — so the agent ran every git operation in its OWN directory: a host could hold exactly one checkout and two remote services would overwrite each other source tree. Each service now builds in its own confined directory, and the name cannot escape it',
      'Remote private-registry deploys no longer hang: the agent built `docker login --password-stdin` so the credential never reaches the process table, but nothing ever wrote to that pipe, so the child sat blocked on a stdin that was never closed until the agent 600-second request timeout',
      'The panel finally lets you choose where a service runs. `serverId` had been accepted by the create and update endpoints all along with no field anywhere in the UI, so multi-node was reachable only from the CLI or a raw API call. A Target node card on the service settings tab lists the registered nodes, explains the limit for PM2 instead of offering a choice that would fail at deploy time, and shows a non-operator the current target read-only rather than calling an endpoint that would 403',
      'PM2 and Nixpacks source builds on a node are refused at queue time with a reason naming the missing capability, instead of being run on the panel host behind the operator back',
      'Remote and S3 build caches are selectable at last: both drivers shipped complete and unit-tested but were never registered on the kernel, so an operator who set the backend to `registry` or `s3` silently kept building against the in-memory LRU. All three are registered now, each reads its connection settings lazily (so saving them in the panel needs no restart), and the panel gained the registry/S3 endpoint and credential fields that were missing entirely',
      'The deploy worker honours the build-cache settings it was ignoring: it took whichever backend happened to register first instead of the one named in `cache_name`, and the master `enabled` switch on that plugin turned nothing off',
      'Build-cache hit rate stops reading 0%: the plugin looked up a key it invented (`service:<id>:no-commit`) that the builder never stores under, so every deploy published a `miss` that could not have been anything else. The hit/miss/error events now come from the build itself, carrying the key it actually consulted',
      'BuildKit builds stop logging a resolve error every time: `--cache-from` was handed the literal `ref=empty` on a first build, and a bare `sha256:` content digest after that — neither names a repository, so buildx could never resolve either. A cache reference that cannot be named is now simply omitted',
      'Four more settings that were saved and never read now work: the per-minute alert cap on the notification dispatcher (it advertised protection against restart storms and capped nothing) and its deploy-success switch, and the template-bundle counter that was pinned at 0. A regression guard now fails the build when any plugin declares a setting nothing reads',
      'Two settings that could never work were removed rather than left as decoration: the account id and tunnel TOKEN on the Cloudflare Tunnels plugin (a password field whose value went nowhere — real tunnel tokens live per tunnel on the Tunnels page), and the metrics retention on the telemetry streamer (the metrics table is deliberately a 24-hour ring, matching the window the API can query)',
      'Two tables stop growing forever: `sessions` gained retention (one row per login, each with an IP and User-Agent, and nothing ever deleted one — the panel filtered dead rows out of its response, so the growth was invisible), and the metric-history retention window is now swept hourly instead of only when an operator clicks Flush. The retention cutoff itself also stopped matching every row and wiping the archive — the trim was destroying the history it existed to keep',
      'The orchestrator stack API answers real questions: `GET /v1/orchestrators/:name/stacks` passed the ORCHESTRATOR name into the driver as the STACK name, so it could only ever ask for a stack coincidentally named after its own orchestrator and returned null for every real one — and a test had pinned that behaviour rather than fixing it. The plural path now lists an orchestrator stacks, and `GET /:name/stacks/:stack` reports one (SDK: `orchestrators.stackStatus(orchestrator, stack)`)',
      'Documentation corrected where it overstated the product: the SSRF egress guard never covered the OIDC issuer or the S3 endpoint, and deliberately does not, because self-hosted Keycloak and MinIO normally sit on private addresses; the agent transport is sealed with a cleartext fallback, not plain HTTP; and the multi-node docs now name exactly what a node runs (docker and compose services) and what it refuses (PM2, Nixpacks) instead of a blanket capability claim',
      'The backup drill no longer OOMs the panel on a multi-gigabyte dump: the MySQL and Postgres validators sniffed dump headers through readFile(), which loads the ENTIRE file, and the drill is member-triggerable — a self-service OOM on the process that hosts the deploy worker. Header sniffing goes through a bounded readHead() open-handle helper, and a source guard keeps whole-file reads out of the module',
      'Config-center strings stop type-flipping across a cache boundary: set() stored plain strings raw while get() re-parsed stored rows on a cache miss, so JSON-ambiguous values (`true`, `123`, `null`) came back as types after a restart while the warm cache returned the exact string — and a metadata-only save then laundered the flip permanently. set() now encodes exactly the strings JSON would misread',
      'Slug collision suffixes stop overflowing the canonical 63-char cap: appending `-<n>` to an already-truncated base stored 64–72 char slugs the schema rejects (service clone loops, migration imports, compose stacks, personal workspaces); slugifyWithSuffix() reserves room for the suffix before truncating only the base',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-09-03',
    title: 'Security Audit Fixes, Real Client IPs & Inline Compose Stacks',
    changes: [
      'Privilege escalation closed: a workspace member could wrap an operator-created PM2/compose service in a scheduled deploy job and reach host command execution on a cron; scheduled deploys now authorize against the service owner exactly like manual and webhook deploys',
      'Real client IPs behind Traefik: without trusting the proxy hop, every rate-limit bucket and audit row collapsed onto the proxy\'s container IP — one tenant could 429 logins and webhooks instance-wide; NINEDEPLOY_TRUST_PROXY (default 1 hop, false for direct exposure) fixes the keying',
      'Production dependency advisories cleared: fast-uri (8 HIGH, SSRF/host confusion via fastify\'s ajv chain) and qs (2 MODERATE, DoS via the MCP SDK\'s express edge) are pinned past their vulnerable ranges — pnpm audit --prod is clean',
      'Editing an env var no longer corrupts secrets: inline saves silently flipped isSecret to false and a typed character overwrote the stored value; the classification is preserved and failures surface as toasts',
      'Self-update no longer crashes the panel: on hosts without /bin/bash the detached updater spawn emitted an uncaught error event mid-request; the failure is now recorded as a finished, failed update',
      'Backups: system export snapshots SQLite with VACUUM INTO (taring the live file could produce unrestorable archives), remote S3 transfers stream (multi-GB dumps no longer buffer in the panel\'s heap), MySQL/MariaDB dumps run --single-transaction (no table locks on live databases), and failed scheduled backups land a failed row plus a notification instead of a log line',
      'Inline Compose stacks: paste YAML instead of cloning — schema-validated (type: compose, mutual exclusion with repoUrl), server-side preflight and dry-run preview, the workspace is re-materialised before every deploy, and a Compose tab offers Save / Save & redeploy',
      'Webhook hardening: replayed provider deliveries are rejected via a 24h delivery-id dedup, and PR preview creation survives the slug race instead of 500ing into provider redelivery',
      'CLI sessions survive past 15 minutes: the refresh token is persisted and 401s retry through a single-flight refresh; server URLs default to https for non-loopback hosts and the JWT secret moves off docker run argv into a 0600 env-file',
      'Panel reliability: deploy logs keep a bounded tail (the per-message re-join froze tabs on multi-MB builds) with stream reconnect, the terminal session survives the fullscreen toggle, storage-denied reads no longer corrupt auth state, and /v1/auth/token answers again',
      'Ops: CI publishes :edge only after tests pass (and the release prune no longer deletes it), services.slug is globally unique at the database level after a one-time dedup, FK indexes replace hot-path full scans, and the schema-drift guard can actually fail',
    ],
  },
  {
    version: '0.5.3',
    date: '2026-09-03',
    title: 'Production ESM Repairs & Working Build Caches',
    changes: [
      'OIDC login works in production again: RS256 verification pulled node:crypto through a lazy require() — undefined in the pure-ESM server package — so every production sign-in died with "require is not defined" while tests stayed green; the same class had silently killed the iptables egress driver\'s on-disk state layer and crashed RegistryBuildCache.store(). All three now use static imports',
      'Remote build caches produce hits: the S3 backend\'s lookup demanded a metadata header on HEAD that store() cannot send, and the registry backend compared the cached layer digest against the manifest\'s own Docker-Content-Digest — both store→lookup round-trips always missed and --cache-from built cold every time; both now GET the marker and compare like-for-like',
      'images prune --keep-last N actually prunes: retention groups were keyed by repo:tag (one image id each), so every group was a singleton and nothing was ever deleted; groups are now per repository',
      'Email template overrides are scoped by workspace AND template name: a password-reset email could render with the workspace-invitation text, and deleting one override wiped the workspace\'s others',
      'Live CPU and RAM on the databases pages: running databases show CPU + memory on the list cards and a Live Resources card in the detail view, polling every 3 seconds; redeploying a running service now asks for confirmation first',
      'Also: exact-length hex magic secrets (SERVICE_PASSWORD_HEX_25 is 25 chars, HEX_1 no longer empty), YAML-ambiguous manifest scalars quoted so round-trips keep string types, monthly cron summaries refuse multi-day day-of-month expressions, PgBouncer status parses pool_mode from the rendered ini, and CLI multi-line pastes feed successive prompts in FIFO order',
    ],
  },
  {
    version: '0.5.2',
    date: '2026-09-02',
    title: 'Uniform Hub Icons & Alert State Seed',
    changes: [
      'Uniform Hub icons: template cards and the detail drawer render a plain slate Package icon instead of 89 arbitrary per-template emojis, matching the panel\'s monochrome design; original brand logos are deliberately not used (licensing and asset hosting for third-party marks)',
      'New alert rules now evaluate from a clean slate: creating a rule seeds its alert_state row so evaluateAlerts can track breaches immediately instead of skipping the first evaluation window',
    ],
  },
  {
    version: '0.5.1',
    date: '2026-09-02',
    title: 'Real Demo, Orchestrator Gate & Watch-Path Reliability',
    changes: [
      'The demo is real: "Load Demo" now creates a single deployable Docker source build of github.com/ersinkoc/nextjs-test (port 3000, /api/health) and queues its first build — replacing rows that claimed to be running with nothing behind them. No PM2, no database; legacy fake demo rows are reaped on first seed',
      'Watch-path webhook matcher hardening: patterns like **a**b**c**d compiled into a regex that backtracked ~C(n,3) steps on long non-matching paths (ReDoS); the matcher is now a bounded DP walk with identical folding semantics, over-long inputs fail open, and branch/tag deletion pushes no longer queue spurious failed deployments',
      'Orchestrator routes are operator-gated: the stack list and stack-status endpoints executed host Docker daemon commands behind bare authentication',
      'Deploy finalize no longer strands the previous container when env decryption fails; the managed-env fingerprint merges into the config snapshot instead of replacing it',
      'Mimosa deep-scan cleanup: the last six false-positive findings resolved at source, and the one supported_static business-logic finding triaged to the operator trust boundary',
    ],
  },
  {
    version: '0.5.0',
    date: '2026-09-02',
    title: 'Plugin Sandboxing, Saga Rollback Hooks & Security Sweep',
    changes: [
      'Isolated Worker Thread plugin runner: third-party and community extensions run inside dedicated node:worker_threads with V8 memory boundaries and an asynchronous RPC bridge, preventing host process blocking or fatal server crashes on plugin exceptions',
      'LIFO Hook Rollback (Saga pattern): pipeline hooks support sequential rollbacks if a downstream interceptor errors or returns a veto (allowOrAbort: false), guaranteeing cleanup of provisioned sidecars and resources',
      'Direct domain events for CRUD operations: services, databases and edge servers now emit typed domain events directly through the kernel event bus alongside the existing audit bridge',
      'Dynamic React UI extension slots: Web Dashboard, Service Overview, and Database Detail views render plugin widgets through the new <PluginSlot /> component',
      'Security sweep: a SAML sign-in bypass (signatures not bound to the assertion) is closed with digest verification and a replay window; community-template ids can no longer traverse out of the data directory; managed git sources are operator-only; database attachments require the member role; domain-preset, build-cache and metric-history mutations are operator-gated; OIDC logins are CSRF-bound with CSPRNG state; private workspaces answer 404 to outsiders instead of confirming their existence',
      'Deploy correctness: compose waits for Docker healthchecks and escapes .env values byte-exact, host-port services deploy sequentially instead of failing on "port already allocated" forever, PM2 domains route through the host gateway instead of 502ing, concurrent database creation on one volume is serialized, and the deploy finalize no longer leaks the previous container when env decryption fails',
    ],
  },
  {
    version: '0.4.9',
    date: '2026-09-01',
    title: 'Hub Image Version Pinning',
    changes: [
      'Pin a template image version at install time: the Hub deploy wizard\'s image field is live for templates (pre-filled with the registry reference) and typing e.g. directus/directus:11.5 deploys that tag. The server accepts only overrides that keep the template\'s registry repository — digest references and cross-repository swaps are refused, because the point is version pinning, not running arbitrary bytes under a vetted template\'s name. Port and volume stay registry-controlled; interrupted installs reconcile cleanly across overrides (the same-template check compares repositories, not exact references); Service → Settings keeps allowing image edits after install for redeploy',
    ],
  },
  {
    version: '0.4.8',
    date: '2026-09-01',
    title: 'Zombie Pipeline Fix on Cancel + Remove',
    changes: [
      'Cancelling a deployment and immediately removing it no longer strands the queue behind a zombie pipeline: the cancel route flips the row terminal immediately while the pipeline stops at its NEXT checkpoint (which can be minutes away inside a docker build or a healthcheck window), and removing the row in that window destroyed the only signal the pipeline polls — isCancelled read the missing row as "not cancelled", so the zombie ran the whole deploy to completion, holding its concurrency slot while the queue\'s #1 entry never claimed. A deployment row that disappears under a running pipeline is now treated as cancelled: the pipeline aborts at the next checkpoint, releases the slot, and the queued deploys behind it proceed',
    ],
  },
  {
    version: '0.4.7',
    date: '2026-09-01',
    title: 'Postgres 18 Data-Directory Layout',
    changes: [
      'Managed postgres 18+ databases start again: the official postgres 18+ images (and pgvector pg18) store data under /var/lib/postgresql/<major>/docker (pg_ctlcluster-compatible layout, docker-library/postgres#1259) and deliberately exit when they detect the classic /var/lib/postgresql/data mount — NineDeploy\'s standard volume mount since forever. The result was a database container in a restart loop: "running and attached" at attach time, gone from DNS a moment later, and the attached app (Directus was the first hit) burning the whole healthcheck window on getaddrinfo EAI_AGAIN against the database hostname. Volumes for majors >= 18 now mount ONCE at /var/lib/postgresql with the data in the versioned subdirectory; majors <= 17 keep the classic layout, and rows already pinned to 17 see no change',
      'The retained-volume re-key sidecar follows the volume label\'s own image instead of the row: the label records the image that initialized the data, which can be an older major than the row\'s configured version — the sidecar previously derived its paths from the row and would have mounted a 16-layout volume with 18 paths',
    ],
  },
  {
    version: '0.4.6',
    date: '2026-09-01',
    title: 'Lockfile Prune & Model B Test Coverage',
    changes: [
      'The lockfile now reflects what the dependency patches mean: the drizzle-kit patch removes @esbuild-kit/esm-loader from its manifest and the archiver-utils patch moves glob to ^13, but pnpm kept resolving those edges from the UNPATCHED manifests — @esbuild-kit/core-utils, @esbuild-kit/esm-loader and the vulnerability-flagged glob@10.5.0 stayed in the lockfile and the installed store. Overrides cut the edges at resolution level (23 packages left the tree; glob resolves into the maintained 13.x line fastify already carries), and the deprecated-dependency guard strips the lockfile\'s overrides: metadata block before grepping — the block legitimately names the packages being removed. Source installs stop pulling the deprecated packages; the guard keeps guarding',
      'The deploy integration tests verify Model B networking instead of Model A: the end-to-end suite still asserted the runtime container sits on the shared ninedeploy mesh and fetched it by name from a throwaway mesh container, but every runtime lives on its own nd-svc-<slug> bridge since v0.3.0, where the mesh neither resolves the name nor routes to it — the pipeline itself passed, the test\'s own verification failed with "bad address". It now verifies reachability the way platform infrastructure (Traefik, the probe container) does — from a container attached to the service\'s bridge, by name — asserts bridge membership, and sweeps the bridge on teardown',
    ],
  },
  {
    version: '0.4.5',
    date: '2026-09-01',
    title: 'Per-Bridge Probe Fix & Security Gates',
    changes: [
      'The healthcheck probe reaches per-service bridges again: Model B (v0.3.0) moved every runtime onto its own nd-svc-<slug> bridge but left ninedeploy-prober on the shared ninedeploy mesh, and Docker drops inter-bridge traffic by default — so any app that binds its port after the 10-second direct-probe grace (first-boot DB migrations; Directus was the first app hit) burned the whole 5-minute window on blind nc timeouts and failed deployment while perfectly healthy (~3s nc + ~3s sleep per attempt ≈ the 300s deadline at ~45 attempts). The prober now joins the runtime\'s networks idempotently before the sibling probe (mirroring Traefik\'s permanent bridge membership; networks it already sits on are skipped), and the first sibling failure logs the probe topology — which networks the container and prober actually sit on — instead of a bare exit code',
      'Container diagnostics no longer lose stderr: logContainerDiagnostic read docker logs through capture(), which returns stdout only — and docker logs exits 0, so everything a crashed boot wrote to stderr (exactly the output that explains the crash) silently vanished from the "Recent container logs" section. It now streams both streams through run()\'s sink',
      'Egress routes are operator-only via a preHandler role check — listing or mutating host-level SNAT/iptables state is not a project-member capability; the suite pins the 403 rejection before any driver method runs',
      'The CORS allowlist excludes localhost origins when NODE_ENV=production — the panel is same-origin in prod; localhost:5173/3000 remain allowlisted in dev only',
      'The workspace owner\'s membership role can no longer be changed in place (403): demoting the owner without transferring workspaces.ownerId could let an admin lock the owner out or leave an owner without owner access — ownership moves only through the transfer route',
      'The 256 MB request-body allowance is scoped to the backup import route instead of global, so login, webhooks and ordinary JSON endpoints cannot allocate a quarter-gigabyte Buffer before authentication runs',
      'Workspace projects require the workspace admin role to mutate: project PATCH/DELETE and shared env mutations demand workspace admin when the project belongs to a workspace — members can still discover and read workspace projects but can no longer rename, re-home or delete them, or edit shared env vars that propagate to every linked service; service cloning requires admin too, since it duplicates encrypted secrets and the full build definition into a caller-owned service',
    ],
  },
  {
    version: '0.4.4',
    date: '2026-09-01',
    title: 'Adoption-Retry Fix & Doctor Accuracy',
    changes: [
      'The retained-volume fix survives a retry now: adoption was gated on status creating, but failures flip the row to error, so the most common follow-up (deploy again) skipped adoption and booted the retained volume\'s stale credentials — the exact crash-loop 0.4.3 set out to close. Databases carry an initialized_at marker (migration 0048) stamped once the volume\'s contents are consistent with THIS row\'s credentials; the gate re-arms while the marker is NULL and the row sits in creating/error',
      'The adoption gate (needsVolumeAdoption) is wired into all four start paths: API create, Hub-provisioning retry (reuseExisting), the explicit start route, and template reconcile — where a retained row left in error by a failed first attempt now goes through adoption again instead of silently starting under credentials nobody has',
      'Doctor no longer mistakes every compose stack\'s network for an orphan: compose networks are ndcmp-<slug>_default and the scan compared the full name against service slugs, never matching — healthy stacks were flagged as "no owner" and a stopped-but-existing stack\'s live network was offered a delete. The project suffix is stripped before the ownership check',
      'Doctor fix refusals answer 409 with the reason instead of an opaque 500 (which hid the message in production): container came back running, volume gained an owner, row gone, deploy moved on now throw proper conflicts; volume deletion also VERIFIES the removal landed, so a failed docker volume rm (volume still mounted) no longer reports Fixed while the volume survives',
      'Re-key progress is visible: capture() silently ignored the heartbeat options, so a slow postgres re-key sat silent in the deploy log for up to its 5-minute timeout; heartbeats now flow through an optional onProgress sink like run() always did',
      'The Doctor panel seeds its query cache with the fix response\'s post-fix report instead of invalidating (a third full scan per click), and the Doctor sidebar link is hidden from non-operators via an operatorOnly nav filter',
    ],
  },
  {
    version: '0.4.3',
    date: '2026-09-01',
    title: 'Retained-Volume Re-Keying & Doctor Mode',
    changes: [
      'Redeploying a template over a deleted database no longer dies silently at the healthcheck — the retained volume was initialized under the old row\'s credentials, so the fresh row (new password) crash-looped the app on auth failures forever. Callers creating a new database row now run adoptRetainedVolume before starting it: postgres is re-keyed via a throwaway single-user sidecar (cluster\'s own image, catalog probe verified in the same session), redis/valkey need nothing (credentials live on the container), and the engines without a re-key path (mysql/mariadb/mongo/clickhouse/rabbitmq/meilisearch) fail up front with the volume\'s provenance and the exact remediation instead of an opaque healthcheck timeout',
      'A labeled retained volume belonging to a different engine is refused outright instead of being mounted as garbage, and creating a database with an existingVolume that already belongs to another database row is refused with a 400 instead of silently sharing (and re-keying) another database\'s data directory',
      'Doctor mode — GET /v1/doctor scans the whole host for what is dead, stale or bloated: exited Hub containers nobody claims, orphaned managed volumes and leftover bridge/compose networks (with ninedeploy.* provenance), services marked running whose runtime container is gone, databases marked running with a dead container or stuck in creating, deploys frozen in queued/building, dangling image layers, oversized builder cache and disk pressure — each with severity, reclaimable size and a one-click repair',
      'POST /v1/doctor/fix re-scans and re-locates the finding against FRESH state before executing, so a stale panel can never delete a volume that gained an owner or kill a container that came back (409 instead); destructive targets are name-family-guarded (nd-* / ninedeploy-* / ndcmp-* only), volume deletion refuses anything whose owner row reappeared, and repairs reuse existing safe paths (managed startDatabase, audited volume removal, age-filtered builder prune, auto-prune) instead of raw prunes',
      'New Doctor page in the System group (operator-gated) with severity-grouped findings, host facts and per-finding fixes with confirmation for the destructive ones; SDK ships the same surface as client.doctor.scan/fix, pinned by client tests',
      'Volume provenance labels: every managed database volume is created with ninedeploy.managed=database plus slug, display name, engine, the exact initializing image, owning user, container name and — for template provisioning — the template id; the Volumes panel shows retainedFrom (name + engine) for ownerless volumes so a retained volume can always be traced back even after the row is gone',
      'Template-generated secrets (secret: true) are now 32 bytes (43 base64url chars) instead of 18, so variables like Directus SECRET or n8n N8N_ENCRYPTION_KEY can never fall under ecosystem 32-character minimums; existing installs keep their stored values — generation only happens on first install',
    ],
  },
  {
    version: '0.4.2',
    date: '2026-08-31',
    title: 'Plugin Audit Fixes & Deploy Queue Management',
    changes: [
      'Post-0.4.1 plugin audit fixes: NotificationsDispatcherPlugin ships a command:palette menuItem (/settings?section=notifications) — it previously had no menu entry at all, so its only path was the hidden /settings?section=plugins URL',
      'TelemetryStreamerPlugin actually POSTs to export_endpoint now — the field was exposed and described as push-based but silently ignored; wires a real fetch() with HMAC-SHA256 signing (X-NineDeploy-Signature: sha256=<hex>) and a per-request AbortSignal timeout, failures land on telemetry.export.error so the audit pipeline picks them up',
      'TelemetryStreamerPlugin wildcard filter drops telemetry.recorded (recursion guard) and telemetry.export.error — a non-2xx response used to re-emit itself as a new record, re-fetch, re-fail and OOM the process; plugin.* / config.* events are dropped from audit data too',
      'Layout sidebar no longer leaks command:palette items into the Extensions group — menus are filtered to sidebar:secondary so Build Cache / Webhook Out / Domain Presets / Sticky IP appear only in the Cmd+K palette, and findGroup picks the longest prefix match so plugin routes like /settings/extensions/<id> stop being swallowed by the System group',
      'ConfigPresetsPlugin menuItem repointed from /settings/presets (no such route) to /settings?section=config, where the preset.list / preset.<id>.values rows actually render',
      'plugin-sdk MenuSlot union extended with database:tabs — the slot was in the kernel runtime type but missing from the SDK, so an external plugin declaring a database-tab menuItem compiled against the SDK and was rejected by the kernel at runtime',
      'Global deploy queue page at /deploys: every in-flight (queued / building / deploying) deploy the caller can see, with per-service position chips (#3 of 5), one-click cancel + remove, 3s auto-refresh and a DeployQueueBadge in the top bar; member sessions see only services they can admin',
      'Multiple queued deploys per service (50-row cap) — the old trigger dedup short-circuited on ANY queued/building match, so a second services deploy click during a long build was silently dropped; split into in-flight (still wins) + per-service queued stack running in enqueue order',
      'Cancel + remove routes on services.deploys — queued deploys stop immediately, in-flight ones stop at the next pipeline step boundary with the previous version still serving; remove refuses in-flight rows (cancel first) and the running row (it carries the digest a rollback re-deploys)',
      'CLI ninedeploy deploys queue and MCP list_queue + remove_deploy tools ship the same queue surface with the matching requiredScopes (read lists, write removes)',
      'SDK ↔ server queue end-to-end test through Fastify app.inject() pins the response shape, so a renamed key or removed field between the SDK schema and the route JSON surfaces in CI',
      'Release pipeline hardened: strict semver tag validation (v0.4.0-foo / v0.4.0+build.1 used to build a real image no install path can reach) and multi-arch (amd64 + arm64) release images so ARM hosts stop hitting "no matching manifest" on docker pull',
    ],
  },
  {
    version: '0.4.1',
    date: '2026-08-31',
    title: 'GHCR Image Pipeline & Post-Sprint 11 Fixes',
    changes: [
      'CI publishes the panel image to GHCR on every push to main: multi-arch (amd64 + arm64) tagged :edge + :main-<sha>, release tag re-tagged :latest so install.sh --docker pulls the most recent artifact, and a preflight docker manifest inspect runs before compose pull so a private GHCR package surfaces a clear one-line error instead of "image pull failed"',
      'Sprint 11 PR #58 coverage push: 200+ tests across 17 new files covering PRs #45–#58. Server 88.12% → 93.53% statements, 86.00% → 88.31% branches; CLI 73% → 84% on the back of the test/index.test.ts restore; SDK 100% on every axis. Thresholds re-bumped to server 93.6/88.4/93/95.1, CLI 83/80/80/83',
      'serviceBridge test premise corrected: docker network ls / inspect preserves the bridge name verbatim ({"nd-svc-foo": {…}}) so the lib\'s literal-string search matches correctly and every ensure/connect/reap/reconcile call is idempotent. The lib was right; the tests were not (16/16)',
      'imageInventory.pruneImages.keepLast semantics: the loop now protects exactly the newest N and leaves the rest as candidates, instead of the previous inverse-of-docstring behavior that made keepLast=0 a silent no-op (45/45)',
      'marketplaceCatalog.decodeKey Node 24 raw 32-byte Ed25519 import: the key is imported as a JWK ({kty: OKP, crv: Ed25519, x: base64url(raw)}), the only form Node\'s key importer accepts for an OKP public key, so the signed marketplace index verifies cleanly (16/16)',
      'localOrchestrator.listStacks service-count regex was always 0 for compose files with body under each service entry. The per-block scanner now counts top-level service lines inside the services: block and excludes 4+-space-indented body lines (24/24)',
      'Coverage follow-ups: stickyIpPlugin 32%→100%, swarmOrchestrator 42%→100% statements / 100% lines (cross-platform in-memory fs shim), localOrchestrator 60%→97% / 98% lines, auth 38%→97%, stats 85%→98%, notifications 0%→100%, backups 0%→97% / 98% lines, manifest 92%→98% / 100% lines, templates hub 0%→30%, servicesCoverage un-skipped (20/20)',
      'CLI vitest testTimeout / hookTimeout lifted to 30s; server vitest the same; web vitest the same. The CI runner is 2–3× slower than a local box and the privilege-gating / patch-merge branches blow past the 5s default and 15s in-suite override',
      'release-publish workflow hardened: the inline empty branches:[] was a parse-time failure (GitHub rejected the workflow at parse with "A sequence was not expected", every run since 4fd2bc4 produced 0 jobs). The key is now redundant with on: push: tags and was dropped. The publish-image job is granted contents:write + packages:write so softprops/action-gh-release can create the GitHub Release',
    ],
  },
  {
    version: '0.3.4',
    date: '2026-08-27',
    title: 'One-Click Self-Update & Honest Records',
    changes: [
      'Operators can upgrade the panel from the dashboard: a banner offers the new release and runs this install\'s own installer for the pinned exact tag — data snapshot, source swap, rebuild, migrations, service restart — detaching through systemd-run so it survives stopping its own unit; failure reports the installer output tail and container-mode installs stay on the manual pull path',
      'Deployment history settles old rows into a new superseded status instead of displaying every past deploy as Running forever, both at finalize time and via a boot-time reconciliation pass',
      'Volume snapshots carry labels (manual / schedule-… / operator tags) that surface across the Backups page together with scope and volume names',
      'Auto-deploy webhook URLs are derived from the Settings panel domain (NINEDEPLOY_DOMAIN, then NINEDEPLOY_PUBLIC_URL) with https mirroring the ACME configuration, and the environment tab warns when stored webhook URLs point at localhost so git providers cannot silently fail delivery',
      'The scheduled-jobs editor is rebuilt around cron presets with human-readable schedule descriptions and next-run chips; environment variables gain a raw .env bulk-edit mode that saves added/updated/removed diffs in parallel',
      'Detaching a volume queues a redeploy instead of demanding the service be stopped first — matching attach/update behavior because Docker cannot hot-swap mounts',
      'Alert rules expose lastEvaluatedAt so the monitoring page can tell "never evaluated" apart from a lapsed collector',
      'Every CI job had been dying in seconds on ERR_PNPM_BAD_PM_VERSION (workflows pinned pnpm 11.22.0 while packageManager declares 11.23.0); the pin is removed in favor of deriving from packageManager, and the Dockerfile installs pinned pnpm via npm now that Node ≥ 26 images no longer bundle corepack',
    ],
  },
  {
    version: '0.3.3',
    date: '2026-08-27',
    title: 'Full-System Audit Hardening',
    changes: [
      'A compose redeploy no longer tears down the deployment it just shipped: the finalize stage recognizes in-place redeploys (the new runtime reuses the previous deterministic id) and skips the retirement instead of running `compose down` against the live project',
      'A cancelled in-place redeploy records reality — the swap already happened under a shared runtime id and cannot be unwound — instead of stopping the still-serving instance',
      'The deploy pipeline verifies its final service-row update actually matched a row; when a service was deleted mid-build the candidate runtime is retired instead of holding its port forever, and deleting a service with a queued or building deployment is refused with 409 up front',
      'A Docker daemon outage at boot no longer crash-exits the panel: the readiness heal stays failed-open and the five-minute Traefik watchdog remains the recovery path',
      'Migration 0031 sorted BEFORE migration 0030 by journal timestamp, so any database migrated during that interim window would never receive it; the entry is reordered monotonically and made replay-safe with IF NOT EXISTS guards',
      'Webhook-triggered deploys (push and PR previews alike) now pass the same host-privilege gate as manual deploys, authorized against the service owner',
      'PR preview environments inherit only non-secret environment variables from their parent; skipped secrets are reported in the webhook response',
      'Preview domain patterns are constrained to the instance wildcard zone with a strict hostname shape before routing goes active — a hostile `*.victim.tld` pattern can no longer claim hosts nobody verified; routing is skipped while the preview still deploys',
      '.ninedeploy manifests can only attach managed databases visible to the deploying service owner — a pushed manifest can no longer inject another tenant database connection string into its runtime env',
      'Every server-side git clone (deploys, PR previews, pre-deploy inspections) passes through one egress gate that refuses private-network remotes; NINEDEPLOY_ALLOW_PRIVATE_EGRESS=1 keeps self-hosted LAN Gitea instances working',
      'Log drains dispatch through the same guarded fetch as notification webhooks, so raw log lines cannot be POSTed at internal or metadata addresses',
      'Pre-upgrade backup archives in install.sh are created operator-only (umask 077 + chmod 600) because they contain master.key',
      'bump-version.js no longer relabels the newest changelog entry via an over-broad regex, warns instead of claiming success when a sync pattern matches nothing, and updates the README version badge',
    ],
  },
  {
    version: '0.3.2',
    date: '2026-08-26',
    title: 'Honest Runtimes',
    changes: [
      'Manifest Creator presets pinned Node 20, Python 3.12 and Go 1.22 — all three lost upstream support months ago; the defaults are now Node 24 (Active LTS), Python 3.14 and Go 1.27, plus Ruby, PHP, Java and Rust',
      'Every version NineDeploy suggests now comes from one curated catalog in @ninedeploy/schemas instead of literals duplicated across the panel and the CLI, and the catalog records the date it was last reviewed so staleness is visible',
      'The Version field is a picker showing each version with its support status; end-of-life and security-only versions stay selectable — reproducing a legacy runtime is a real need — but carry an advisory naming the recommended pin',
      "The manifest's build sections (runtime, phases, build) are not applied at build time: the pipeline applies only routes, alerts and database. The docs and the Runtime section now say so instead of implying a pin that never happens",
      'Every runtime pin the nixpacks.toml generator produced was broken — wrong nixpkgs attribute names for Go and Ruby, nonsense for any patch-level pin, and a package list that replaced the provider toolchain instead of extending it',
      'Version pins now go only through the provider environment variables Nixpacks 1.41.0 actually reads, and a pin it cannot honour returns a specific warning rather than silently building a different version',
    ],
  },
  {
    version: '0.3.1',
    date: '2026-08-26',
    title: 'Boot Fix For 0.3.0',
    changes: [
      "0.3.0 could not start: every boot died with \"Cannot access 'NETWORK' before initialization\" and systemd restarted it forever",
      'Two engine modules imported each other and one evaluated the other\'s constant at module scope, so the entry graph decided whether it was initialised yet; the shared Docker names moved to a module that imports nothing',
      'A new test walks the server module graph and fails on any import cycle — a type checker cannot see a temporal dead zone, so this could only surface in production',
      'A readiness failure now prints systemd status, the last 60 journal lines and the health port owner, and a crash-loop ends the wait immediately instead of sitting through the whole window',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-08-26',
    title: 'Tags, Volumes & The .ninedeploy Manifest',
    changes: [
      'Tags across three dimensions: a service belongs to many projects, workspaces and labels at once, and the top-bar filter composes all three (AND across groups, OR within one)',
      "A Projects page and a Labels page manage the flat tag lists; a per-service Tags card edits one service's whole membership through PUT /v1/services/:id/tags",
      'Per-service volume attachments: mount any number of managed Docker volumes at explicit container paths, read-only or read-write, with a uniqueness guard on both path and volume',
      'Volume backups: snapshot, restore and download any managed volume, reusing the database backup destination for off-site copies and refusing to restore under a live service',
      "`.ninedeploy` manifest: `ninedeploy manifest init|validate|show` scaffolds, schema-checks and prints the repo-side manifest, with the server's own secret scan rejecting credential-shaped values before they reach git (the deploy pipeline applies the file itself on every deploy; the on-demand `apply` endpoint is still pending)",
      'Private repository deployment from the CLI: `ninedeploy sources` and `ninedeploy webhooks` manage encrypted credentials, server-generated SSH deploy keys and auto-deploy webhooks',
      "Workspace invitations for addresses that have no account yet, accepted automatically on the invitee's next login or registration",
      "Self-healing runtime state: every 60 seconds the panel revives stopped containers, a dead PM2 daemon and stopped PM2 processes instead of reporting a dead service as running",
      "Fixed the upgrade that blocked every install from 0.2.2 onward — a boot-time column collided with its own later migration and the panel never started",
      "Implemented the three managed-volume helpers the backup routes imported but that had never been written; the server package did not compile without them",
      'Finished the service tagging migration in the services API, which still read the removed single-project column',
      'An Organize navigation group makes Workspaces, Projects and the new Labels page reachable; projects had a route with no menu entry and labels had no management screen at all',
      'Volume snapshots, restore and download are available for every volume from Data > Volumes, including retained volumes that belong to no service',
      'The command palette indexes Manifest Creator, Workspaces, Projects, Labels, Networks, Traefik and Docker, and ranks label matches above type matches so a single letter no longer fills the result list with navigation entries',
      'install.sh installs the published release tarball instead of cloning, resolves the newest tag through three independent sources, clears stale build output before rebuilding, and verifies the built version against the requested tag',
    ],
  },
  {
    version: '0.2.36',
    date: '2026-08-20',
    title: 'Legacy Provisioning Recovery',
    changes: [
      'Deployments stranded by the browser-owned provisioning flow from 0.2.34 are detected by their provisioning marker and requeued on worker startup, without waiting for the stale-deployment timeout',
    ],
  },
  {
    version: '0.2.35',
    date: '2026-08-20',
    title: 'Durable Hub Provisioning',
    changes: [
      'Services persist their trusted Hub template ID so the worker can reconstruct and reconcile required database dependencies after a process or host restart',
      'Preparing a Hub service is now a durable queue operation: database startup, attachment, environment reconciliation and deployment continue even if the browser disconnects',
      'Stale building deployments are requeued for idempotent recovery instead of being marked failed automatically',
    ],
  },
  {
    version: '0.2.34',
    date: '2026-08-20',
    title: 'Immediate Hub Handoff',
    changes: [
      'Pressing Deploy in a Hub modal prepares the service identity, closes the modal and navigates straight to the Deploys tab instead of waiting for image and database provisioning',
      'The fast prepare response creates a building deployment row immediately so the Deployments tab can display and poll it while dependencies are provisioned',
      'Provisioning continues in the background after navigation; completion and failure refresh service state and raise a toast without reopening the modal',
    ],
  },
  {
    version: '0.2.33',
    date: '2026-08-20',
    title: 'Dependency Readiness',
    changes: [
      'Runtime deployment recovers the trusted application-specific database mapping from the bundled template contract instead of falling back to localhost',
      'A service whose attached database is not running fails before its application container starts, reporting the exact attachment readiness count instead of restart-looping',
      'Deployment logs list the injected managed-database environment key names without exposing credential values',
    ],
  },
  {
    version: '0.2.32',
    date: '2026-08-20',
    title: 'Canonical Hub Provisioning',
    changes: [
      'The API owns service configuration, environment reconciliation, database startup, attachment and queueing as one ordered operation; the panel no longer coordinates them separately',
      'Hub images, ports, mounts, commands, socket access and database mappings resolve exclusively from the trusted server registry and cannot be overridden by the panel request',
      'Repeating an install with the same name reuses the caller-owned failed service, database, volume and attachment instead of creating duplicates',
      'Directus, Ghost, Hasura, Matomo, Umami, Vikunja, WordPress and YOURLS all run through the same provisioning contract and regression suite',
    ],
  },
  {
    version: '0.2.31',
    date: '2026-08-20',
    title: 'Reliable Ghost Deployment',
    changes: [
      'Ghost 5 Hub installs automatically provision MySQL and inject every required nested database connection setting',
      'A failed Ghost service created from the older incomplete template can be repaired in place by repeating the same Hub install',
      'Healthchecks stop early when a container exits or remains in a restart loop and include redacted exit diagnostics and recent logs',
      'Ghost 5 with MySQL 8.4 passed an isolated real-container startup and port 2368 smoke test',
    ],
  },
  {
    version: '0.2.30',
    date: '2026-08-20',
    title: 'Service Domain Launcher',
    changes: [
      'Services with configured domains expose a consistent open-site action across service lists, dashboard health and activity, service detail, and topology views',
      'Opening a service always shows a confirmation modal before navigating to a new browser tab',
      'Services with multiple domains show every HTTPS or HTTP destination, route path, and an explicit selection instead of guessing a primary domain',
      'Domain launchers share one cached global domain query and refresh immediately after domain configuration changes',
    ],
  },
  {
    version: '0.2.29',
    date: '2026-08-20',
    title: 'Guided Cloudflare Tunnel Setup',
    changes: [
      'The Tunnels panel explains why public hostname routing requires Cloudflare Tunnel with cloudflared rather than Mesh or private network connectors',
      'A numbered guide covers remotely managed tunnel creation, connector token selection and NineDeploy startup',
      'The exact Traefik HTTP origin is shown with one-click copy and matching Published application route instructions',
      'Domain guidance explicitly requires the same hostname with NineDeploy SSL disabled because Cloudflare terminates public TLS',
      'Connector tokens are entered through a password field with API key and Tunnel ID warnings',
    ],
  },
  {
    version: '0.2.28',
    date: '2026-08-20',
    title: 'Full Curated Hub',
    changes: [
      'All 88 schema-valid curated application templates are visible and deployable again',
      'Fifteen isolated-smoke-tested apps retain a clear Verified badge while 73 others are labelled Community',
      'Hub filters expose All, Verified and Community counts without conflating manifest validation with runtime certification',
      'Community detail and deployment screens show an explicit pre-deploy review warning',
    ],
  },
  {
    version: '0.2.27',
    date: '2026-08-20',
    title: 'Deterministic Container Routing',
    changes: [
      'Nixpacks source deployments default to container port 3000 and receive the same value through PORT',
      'Single EXPOSE ports are detected automatically for Dockerfile and image deployments',
      'Runtime healthchecks, direct publishing and Traefik now share one resolved internal port',
      'The Network tab exposes an explicit Container Port and Traefik Target control for manual overrides',
    ],
  },
  {
    version: '0.2.26',
    date: '2026-08-20',
    title: 'Reliable Source Builds',
    changes: [
      'Ubuntu installs provision the real Nixpacks 1.37.0 CLI from official release assets with architecture-specific SHA-256 verification',
      'NineDeploy runtime and remote-agent images include the same verified Nixpacks CLI for consistent source builds',
      'Source builds no longer attempt to execute the Nixpacks build-base image as a CLI container',
      'A missing build CLI now fails immediately with an actionable installer repair instruction',
    ],
  },
  {
    version: '0.2.25',
    date: '2026-08-20',
    title: 'Visible Deployment Progress',
    changes: [
      'Silent deployment commands emit elapsed-time activity heartbeats so the panel never presents active work as frozen',
      'Normal stdout and stderr postpone heartbeats, preserving readable logs while still detecting genuinely silent work',
      'Registry export, filesystem packaging, and Docker image import identify their current recovery phase every 15 seconds',
      'Heartbeat labels never expose subprocess arguments that may contain credentials or other sensitive values',
    ],
  },
  {
    version: '0.2.24',
    date: '2026-08-20',
    title: 'Containerd Transfer Platform Recovery',
    changes: [
      'Native snapshot recovery explicitly selects the host Linux platform for multi-platform OCI image indexes',
      'Containerd 2 transfer API unpack failures retry through ctr local mode before falling back to direct registry export',
      'Native image mounts use the same explicit platform so WordPress and other multi-architecture images resolve consistently',
    ],
  },
  {
    version: '0.2.23',
    date: '2026-08-20',
    title: 'Hub-Wide Snapshot Recovery Certification',
    changes: [
      'Every runtime-certified Hub application now passes forced snapshotter-independent export, import, startup and TCP probing',
      'WordPress plus MySQL and Directus plus PostgreSQL pass the same recovery path with real database initialization and wiring',
      'Docker Hub, GHCR and Codeberg registry images are covered by one image-independent recovery implementation',
      'The checksum-verified registry tool is reused safely within the server process and pinned to a BusyBox-compatible release',
    ],
  },
  {
    version: '0.2.22',
    date: '2026-08-20',
    title: 'Snapshotter-Independent Registry Recovery',
    changes: [
      'Images recover directly from their registry when both Docker overlayfs and containerd native snapshotters are unusable',
      'The fallback uses a pinned and checksum-verified crane binary to flatten the image into a fresh single-layer chain',
      'OCI environment, entrypoint, command, ports, volumes, labels, user, working directory and healthcheck metadata are retained',
      'A destructive-state-free MySQL 8.4 smoke test proves registry export, Docker import and database readiness end to end',
    ],
  },
  {
    version: '0.2.21',
    date: '2026-08-20',
    title: 'Runtime-Certified Template Hub',
    changes: [
      'The Hub fails closed and exposes only templates that passed isolated container startup and declared-port probes',
      'Fifteen application templates are runtime-certified; the rest stay hidden until tested individually',
      'A reusable smoke runner verifies real image, environment, command, volume, process and Docker-network port behavior',
      'Website and product copy no longer confuse registry manifest checks with runtime verification',
    ],
  },
  {
    version: '0.2.20',
    date: '2026-08-20',
    title: 'Honest and Working Template Deployments',
    changes: [
      'The Hub now publishes only templates compatible with its current one-application and optional one-database deployment model',
      'WordPress, Directus, and every supported database template receive their image-specific connection environment variables',
      'CLI template deploys provision and attach managed databases before the application is queued',
      'All 88 bundled images pass a real OCI manifest check, with corrected Memos, Forgejo, and Kavita references',
      'Real WordPress plus MySQL and Directus plus PostgreSQL container boots validate the database mappings',
    ],
  },
  {
    version: '0.2.19',
    date: '2026-08-20',
    title: 'End-to-End Ubuntu Runtime Reliability',
    changes: [
      'Every internal helper image is explicitly prepared through the shared Docker and containerd recovery path before docker run',
      'Traefik startup, updates, remote agents, database studios, tunnels, health probes, and volume tools now share one reliable image lifecycle',
      'Ubuntu installs use a consistent elevated Docker command path, run the host control-plane with the privileges its Docker trust boundary requires, and verify the real HTTP ingress',
      'Automatically assigned wildcard domains enable HTTPS whenever an ACME account is configured',
    ],
  },
  {
    version: '0.2.18',
    date: '2026-08-20',
    title: 'Targeted Containerd Snapshot Repair',
    changes: [
      'Unused committed overlayfs snapshots that block image extraction are safely removed through containerd dependency checks',
      'Recovery commands explicitly connect to Docker external or daemon-managed containerd sockets',
      'Deployment errors expose the native recovery failure when every snapshot recovery strategy fails',
    ],
  },
  {
    version: '0.2.17',
    date: '2026-08-20',
    title: 'Managed Database Snapshot Recovery',
    changes: [
      'Managed database images are explicitly pulled through the Docker 29 and containerd snapshot recovery path before startup',
      'MySQL and other database deployments no longer rely on docker run implicit image pulls that fail opaquely with code 125',
      'Image preparation failures stop before existing container state or temporary secret environment files are mutated',
    ],
  },
  {
    version: '0.2.16',
    date: '2026-08-20',
    title: 'Panel Autofill Rejection',
    changes: [
      'Authenticated panel inputs reject browser and password-manager autofill, autocomplete, autocorrect, and spellcheck',
      'Dynamically mounted dialog and plugin fields inherit the same no-autofill policy',
      'The Settings filter stays locked until deliberate interaction and clears detected browser autofill injection',
    ],
  },
  {
    version: '0.2.15',
    date: '2026-08-20',
    title: 'Persistent Docker Snapshot Recovery',
    changes: [
      'Persistent Docker 29 and containerd overlayfs snapshot collisions recover through the isolated native snapshotter',
      'Recovered images retain their runtime metadata, filesystem ownership, capabilities, ACLs, and extended attributes',
      'Snapshot recovery never deletes or hides existing Docker images, containers, or volumes',
    ],
  },
  {
    version: '0.2.14',
    date: '2026-08-20',
    title: 'End-to-End Hub Retry Recovery',
    changes: [
      'Interrupted Hub deployments resume only a matching caller-owned idle service',
      'Template environment variables, managed databases, and database attachments are safely reconciled on retry',
      'Retries no longer fail on partial-install service, environment, database, container, or attachment collisions',
    ],
  },
  {
    version: '0.2.13',
    date: '2026-08-20',
    title: 'Reliable Hub Database Provisioning',
    changes: [
      'Managed database startup reconciles Docker daemon state after a late docker run code 125 failure',
      'A database container that is already running is adopted instead of leaving its control-plane row in an error state',
      'Hub template retries safely resume only a matching caller-owned database and no longer collide with its existing slug or container name',
    ],
  },
  {
    version: '0.2.12',
    date: '2026-08-20',
    title: 'Automatic Docker Image Port Recovery',
    changes: [
      'Failed Docker healthchecks probe TCP ports declared by image metadata and recover an incorrect configured internal port automatically',
      'A recovered image port is persisted so Traefik and future deployments use the corrected value',
      'n8n image deployments configured with port 80 automatically recover to the image-declared 5678/tcp port',
    ],
  },
  {
    version: '0.2.1',
    date: '2026-08-18',
    title: 'CLI Package Rename & NPM Distribution Release',
    changes: [
      'Official npm publication setup for CLI and monorepo packages',
      'Renamed CLI package to ninedeploy for seamless `npx ninedeploy` and global npm install',
      'Public npm packaging configuration for @ninedeploy/sdk, @ninedeploy/schemas, @ninedeploy/plugin-sdk, and @ninedeploy/mcp',
      'Updated workspace release automation scripts and package dependency resolution',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-08-18',
    title: 'Workspaces, OIDC SSO, Microkernel & MCP Engine',
    changes: [
      'Multi-tenant Workspaces with 4-tier RBAC (Owner, Admin, Member, Viewer)',
      'Enterprise Single Sign-On via OpenID Connect (Google, GitHub, Keycloak, Okta)',
      'Hardware-backed Passkeys (WebAuthn / FIDO2) biometric authentication',
      'Microkernel event bus and waterfall hook pipeline (deploy.before / deploy.after)',
      'Central Configuration Center with Dual-Vault AES-256-GCM encryption & key rotation',
      'Plugin SDK with MenuRegistry and ServiceRegistry driver interchange',
      '35-tool Model Context Protocol (MCP) server for AI coding assistants (Claude, Cursor, Antigravity, Cline)',
      '100+ verified 1-click application templates with automated dependency resolution',
      'Live Container File Browser with drag-and-drop file operations',
      'Real-time Log Drains forwarding structured logs to Syslog, HTTP, and Datadog',
      'Ephemeral PR preview staging environments and 1-click demo stack',
    ],
  },
  {
    version: '0.1.0',
    date: '2026-08-14',
    title: 'Initial pre-release',
    changes: [
      'Deploy engine: Git repo (public/private) + Docker image, PM2 + Docker targets',
      'Zero-downtime blue-green releases with health checks and automatic rollback',
      'Auto-deploy webhooks: GitHub, GitLab, Gitea (HMAC verified, replay-safe)',
      'Live deploy logs via WebSocket + container exec terminal (xterm.js)',
      'Managed databases: PostgreSQL, MySQL, Redis, MongoDB (encrypted credentials)',
      'Backups (encrypted at rest) with daily scheduler and restore',
      'Traefik routing with automatic HTTPS (Let\'s Encrypt) and Cloudflare Tunnels',
      'Multi-user RBAC, audit log, rate limiting, master-key rotation',
      'Web dashboard, CLI, template hub (48 one-click apps)',
      'SQLite — zero external dependencies; 100% test coverage enforced in CI',
      'Metric-driven alert rules (CPU/memory/cert-expiry) with duration windows, cooldown, and recovery notifications',
      'New notification channels: Slack, ntfy, and email (SMTP with encrypted credentials)',
      'Retry with exponential backoff for failed notification deliveries',
      'TLS certificate expiry tracking on the Domains page with warning badges',
      'ACME email configurable from Settings (env fallback preserved)',
      'CLI parity: env, domains, volumes, backups, alerts, users, activity, system export/import, streaming logs',
      'Data-driven template registry: JSON bundle + swappable source (URL/path) with caching and offline fallback',
      'Wildcard SSL via ACME DNS-01 (Cloudflare, DigitalOcean, Hetzner, Linode, Gandi, DuckDNS) with encrypted API tokens',
      'Parallel deploy slots (NINEDEPLOY_DEPLOY_CONCURRENCY, 1-8) with per-service serialization',
      'Notification channel editing (pause/resume, rename, event filter) in Settings',
      'Dashboard/Services routing fix, service Danger Zone (delete), in-use volume deletion protection (409)',
      'Template safety: auto-generated secrets (no more changeme), requirement hints, and auto-provisioned databases for DB-dependent apps',
      'Healthchecks fall back to sibling-container TCP probing so deploys work on Docker Desktop (macOS/Windows) too',
      'Template registry verified against real deployments: per-template commands, docker-socket flag, arm64/port fixes, auto-generated secrets, auto-provisioned databases',
      'ACME staging directory support (NINEDEPLOY_ACME_CA_SERVER) and a hardened, installer-rendered systemd unit',
      'Integration test coverage: MySQL/Redis/MongoDB backup round-trips, end-to-end deploy + rollback',
      'Tabbed Service Detail page: metrics sparklines, runtime metadata, service settings + build config editing, resource limits UI, per-domain SSL toggle, and a per-service activity trail',
      'PATCH /services/:id now persists build-config changes (previously parsed and discarded); GET returns build config + resource limits',
      'Dokploy-parity wave: deployment cancellation (checkpointed pipeline), watch-path webhooks (monorepo filters), MariaDB engine, www→apex redirects + custom response headers, TOTP two-factor authentication, S3-compatible off-site backup destinations (SigV4 client, zero deps), cron-scheduled jobs (deploys + container commands, croner), private-registry credentials (docker login via stdin), Docker Compose deployments, and an agent-based multi-server foundation (typed-operation protocol — remote hosts never accept raw commands)',
      'Password reset: forgot-password flow (single-use 30-min tokens, optional SMTP delivery via the notifier) + admin-issued one-time reset links (Users page / CLI)',
      'Per-account login lockout (5 failed attempts → 15 min) complementing the per-IP rate limit',
      'Release-channel installer: defaults to the latest release tag (--version pin, --channel main edge), snapshots .data before upgrades and health-checks the restart',
      'Update check: GET /v1/system/update-check (admin), About-page badge, `ninedeploy system update-check`',
      'About endpoint no longer leaks instance counts to unauthenticated callers',
      'Hardened installer-rendered systemd service with HTTP readiness verification',
      'First-admin bootstrap is transactional (no dual-admin race)',
    ],
  },
];

export const ABOUT = {
  name: 'NineDeploy',
  version: VERSION,
  description: 'Self-hosted deployment platform — deploy apps from Git or Docker Hub in one click.',
  license: 'MIT',
  repo: 'https://github.com/ninedeploy/ninedeploy',
  docs: 'https://github.com/ninedeploy/ninedeploy#readme',
  techStack: [
    { category: 'Runtime', items: ['Node.js ≥ 22.13', 'TypeScript 7 (strict)'] },
    { category: 'Backend', items: ['Fastify 5', 'Zod 4', 'WebSocket', 'Drizzle ORM'] },
    { category: 'Database', items: ['SQLite (node:sqlite)'] },
    { category: 'Frontend', items: ['React 19', 'Vite 8', 'Tailwind v4', 'React Flow'] },
    { category: 'Deploy', items: ['Docker (BuildKit)', 'PM2', 'Traefik v3', 'Cloudflare Tunnel'] },
    { category: 'Security', items: ['AES-256-GCM', 'JWT', 'Argon2', 'HMAC webhooks'] },
  ],
  changelog: CHANGELOG,
};
