import {
  createApiToken,
  forgotPassword,
  login,
  oidcProviderCreate,
  oidcProviderUpdate,
  passkeyLoginVerify,
  passkeyRegisterVerify,
  passwordChange,
  passwordResetWithToken,
  refresh,
  register,
  stepUp,
  twoFactorDisable,
  twoFactorEnable,
  twoFactorSetup,
} from '@ninedeploy/schemas';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: auth (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const authSpecs: RouteSpecMap = {
  'GET /v1/auth/status': {
    summary: 'Whether the instance is initialized and open registration is on',
    tag: 'auth',
    floor: 'public',
    responseType: '{ initialized: boolean }',
  },
  'POST /v1/auth/login': {
    summary: 'Sign in with email and password',
    tag: 'auth',
    floor: 'public',
    body: login,
    responseType: 'Session',
    validation: 'zod',
    sensitive: true,
  },
  'POST /v1/auth/register': {
    summary: 'Register an account (when open registration is on)',
    tag: 'auth',
    floor: 'public',
    body: register,
    responseType: 'Session',
    validation: 'zod',
    sensitive: true,
  },
  'POST /v1/auth/refresh': {
    summary: 'Exchange a refresh token for a new session',
    tag: 'auth',
    floor: 'public',
    body: refresh,
    responseType: 'Session',
    validation: 'zod',
    sensitive: true,
  },
  'POST /v1/auth/forgot-password': {
    summary: 'Request a password reset email',
    tag: 'auth',
    floor: 'public',
    body: forgotPassword,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'POST /v1/auth/reset-password': {
    summary: 'Complete a password reset with its single-use token',
    tag: 'auth',
    floor: 'token',
    body: passwordResetWithToken,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'GET /v1/auth/oidc/providers/public': {
    summary: 'List the OIDC providers shown on the sign-in page',
    tag: 'auth',
    floor: 'public',
    responseType: 'OidcPublicProvider[]',
  },
  'GET /v1/auth/oidc/:slug/login': {
    summary: 'Start an OIDC sign-in',
    tag: 'auth',
    floor: 'public',
  },
  'GET /v1/auth/oidc/:slug/callback': {
    summary: 'OIDC sign-in callback (redirect)',
    tag: 'auth',
    floor: 'token',
    sensitive: true,
  },
  'POST /v1/auth/oidc/:slug/callback': {
    summary: 'OIDC sign-in callback (code exchange)',
    tag: 'auth',
    floor: 'token',
    responseType: 'Session',
    sensitive: true,
  },
  'POST /v1/auth/passkey/login/options': {
    summary: 'Start a passkey sign-in ceremony',
    tag: 'auth',
    floor: 'public',
    responseType: '{ options: string }',
  },
  'POST /v1/auth/passkey/login/verify': {
    summary: 'Finish a passkey sign-in ceremony',
    tag: 'auth',
    floor: 'token',
    body: passkeyLoginVerify,
    responseType: 'Session',
    validation: 'zod',
    sensitive: true,
  },
  'GET /v1/auth/me': {
    summary: 'The signed-in user',
    tag: 'auth',
    floor: 'self',
    responseType: 'PublicUser',
  },
  'POST /v1/auth/logout': {
    summary: 'Sign out everywhere (revokes every outstanding JWT)',
    tag: 'auth',
    floor: 'self',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/auth/password': {
    summary: "Change the signed-in user's password",
    tag: 'auth',
    floor: 'self',
    body: passwordChange,
    responseType: 'PasswordChangeResult',
    validation: 'zod',
  },
  'POST /v1/auth/2fa/setup': {
    summary: 'Generate a TOTP secret (step-up required)',
    tag: 'auth',
    floor: 'self',
    body: twoFactorSetup,
    responseType: '{ secret: string; otpauthUri: string }',
    validation: 'zod',
    sensitive: true,
  },
  'POST /v1/auth/2fa/enable': {
    summary: 'Enable TOTP two-factor authentication',
    tag: 'auth',
    floor: 'self',
    body: twoFactorEnable,
    responseType: '{ ok: boolean; totpEnabled: boolean }',
    validation: 'zod',
  },
  'POST /v1/auth/2fa/disable': {
    summary: 'Disable TOTP two-factor authentication',
    tag: 'auth',
    floor: 'self',
    body: twoFactorDisable,
    responseType: '{ ok: boolean; totpEnabled: boolean }',
    validation: 'zod',
  },
  'GET /v1/auth/passkey': {
    summary: "List the signed-in user's passkeys",
    tag: 'auth',
    floor: 'self',
    responseType: 'PasskeyCredential[]',
  },
  'DELETE /v1/auth/passkey/:id': {
    summary: "Remove one of the signed-in user's passkeys",
    tag: 'auth',
    floor: 'self',
  },
  'POST /v1/auth/passkey/register/options': {
    summary: 'Start a passkey registration ceremony (step-up required)',
    tag: 'auth',
    floor: 'self',
    body: stepUp,
    responseType: '{ options: string }',
    validation: 'zod',
  },
  'POST /v1/auth/passkey/register/verify': {
    summary: 'Finish a passkey registration ceremony',
    tag: 'auth',
    floor: 'self',
    body: passkeyRegisterVerify,
    responseType: 'PasskeyCredential',
    validation: 'zod',
  },
  'GET /v1/auth/sessions': {
    summary: "List the signed-in user's sessions",
    tag: 'auth',
    floor: 'self',
    responseType: 'ActiveSession[]',
  },
  'DELETE /v1/auth/sessions/:id': {
    summary: "Revoke one of the signed-in user's sessions",
    tag: 'auth',
    floor: 'self',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/auth/token': {
    summary: 'Introspect the current bearer token (kind and scopes)',
    tag: 'auth',
    floor: 'self',
    responseType: 'TokenIntrospection',
  },
  'GET /v1/auth/tokens': {
    summary: "List the signed-in user's API tokens",
    tag: 'auth',
    floor: 'self',
    responseType: 'ApiToken[]',
  },
  'POST /v1/auth/tokens': {
    summary: 'Create an API token (the plaintext is returned once)',
    tag: 'auth',
    floor: 'self',
    body: createApiToken,
    responseType: 'CreatedApiToken',
    validation: 'zod',
    sensitive: true,
  },
  'DELETE /v1/auth/tokens/:id': {
    summary: "Revoke one of the signed-in user's API tokens",
    tag: 'auth',
    floor: 'self',
  },
  'POST /v1/auth/oidc/:slug/link': {
    summary: 'Link an OIDC identity to the signed-in user',
    tag: 'auth',
    floor: 'self',
    responseType: '{ authUrl: string }',
  },
  'GET /v1/auth/oidc/providers': {
    summary: 'List OIDC providers',
    tag: 'auth',
    floor: 'operator',
    responseType: 'OidcProviderEntry[]',
  },
  'POST /v1/auth/oidc/providers': {
    summary: 'Create an OIDC provider',
    tag: 'auth',
    floor: 'operator',
    body: oidcProviderCreate,
    responseType: 'OidcProviderEntry',
    validation: 'zod',
  },
  'PATCH /v1/auth/oidc/providers/:id': {
    summary: 'Update an OIDC provider',
    tag: 'auth',
    floor: 'operator',
    body: oidcProviderUpdate,
    responseType: 'OidcProviderEntry',
    validation: 'zod',
  },
  'DELETE /v1/auth/oidc/providers/:id': {
    summary: 'Delete an OIDC provider',
    tag: 'auth',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/sso/:name/login': {
    summary: 'Start an SSO sign-in for a configured provider',
    tag: 'sso',
    floor: 'authed',
  },
  'GET /v1/sso/:name/callback': {
    summary: 'SSO sign-in callback',
    tag: 'sso',
    floor: 'authed',
    queryType: '{ code?: string; state?: string; error?: string; error_description?: string }',
    validation: 'handler',
  },
  'POST /v1/sso/:name/saml-callback': {
    summary: 'SAML assertion consumer (answers saml_unavailable)',
    tag: 'sso',
    floor: 'authed',
    bodyType: '{ SAMLResponse?: string }',
    validation: 'handler',
  },
  'GET /v1/sso/providers': {
    summary: 'List SSO providers',
    tag: 'sso',
    floor: 'operator',
  },
  'POST /v1/sso/providers': {
    summary: 'Create an SSO provider',
    tag: 'sso',
    floor: 'operator',
    bodyType: "{ type: 'oidc' | 'saml'; name: string; config: Record<string, unknown> }",
    responseType: "{ ok: boolean; id?: number; name?: string; type?: 'oidc' | 'saml'; error?: string; }",
    validation: 'handler',
  },
  'DELETE /v1/sso/providers/:id': {
    summary: 'Delete an SSO provider',
    tag: 'sso',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/scim/tokens': {
    summary: 'List SCIM tokens',
    tag: 'scim',
    floor: 'operator',
  },
  'POST /v1/scim/tokens': {
    summary: 'Create a SCIM token for a workspace (the plaintext is returned once)',
    tag: 'scim',
    floor: 'operator',
    bodyType: '{ name?: string; workspaceId?: number }',
    responseType: '{ id: number; token: string }',
    validation: 'handler',
    sensitive: true,
  },
  'DELETE /v1/scim/tokens/:id': {
    summary: 'Revoke a SCIM token',
    tag: 'scim',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
};
