import {
  backupDestinationCreate,
  backupDestinationObjectsQuery,
  backupDestinationPatch,
  backupPolicyInput,
  createDatabase,
  databaseImportCreate,
  publicAccessPut,
  setLimits,
} from '@ninedeploy/schemas';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: databases (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const databasesSpecs: RouteSpecMap = {
  'GET /v1/databases': {
    summary: 'List databases',
    tag: 'databases',
    floor: 'authed',
    queryType: '{ projectId?: string }',
    validation: 'handler',
  },
  'POST /v1/databases': {
    summary: 'Create a database',
    tag: 'databases',
    floor: 'member',
    body: createDatabase,
    responseType: 'ManagedDatabase',
    validation: 'zod',
  },
  'GET /v1/databases/:id': {
    summary: 'Get a database',
    tag: 'databases',
    floor: 'viewer',
    responseType: 'DatabaseDetail',
    mcp: { name: 'get_database', description: 'Get one managed database: engine, version, status, project and resource limits. Never the password or connection URI.', readOnly: true },
  },
  'DELETE /v1/databases/:id': {
    summary: 'Delete a database',
    tag: 'databases',
    floor: 'admin',
    queryType: '{ force?: string }',
    validation: 'handler',
  },
  'GET /v1/databases/:id/logs': {
    summary: 'Recent logs of a database container',
    tag: 'databases',
    floor: 'viewer',
    queryType: '{ lines?: string }',
    validation: 'handler',
  },
  'GET /v1/databases/:id/storage': {
    summary: 'Disk usage of a database',
    tag: 'databases',
    floor: 'viewer',
    responseType: '{ sizeBytes: number }',
  },
  'PATCH /v1/databases/:id/limits': {
    summary: "Set a database's resource limits",
    tag: 'databases',
    floor: 'member',
    body: setLimits,
    validation: 'zod',
  },
  'POST /v1/databases/:id/start': {
    summary: 'Start a database',
    tag: 'databases',
    floor: 'member',
  },
  'POST /v1/databases/:id/stop': {
    summary: 'Stop a database',
    tag: 'databases',
    floor: 'member',
  },
  'POST /v1/databases/:id/restart': {
    summary: 'Restart a database',
    tag: 'databases',
    floor: 'member',
  },
  'GET /v1/databases/:id/credentials': {
    summary: "Reveal a database's password and connection URI",
    tag: 'databases',
    floor: 'admin',
    responseType: 'DatabaseCredentialsWithPublic',
    sensitive: true,
  },
  'GET /v1/databases/:id/backups': {
    summary: "List a database's backups",
    tag: 'backups',
    floor: 'viewer',
    responseType: 'Backup[]',
    mcp: { name: 'list_backups', description: 'Backups of one managed database (newest first): status, size, destination and timestamps.', readOnly: true },
  },
  'POST /v1/databases/:id/backups': {
    summary: 'Back up a database now',
    tag: 'backups',
    floor: 'admin',
    responseType: 'Backup',
  },
  'POST /v1/databases/:id/backups/:bid/restore': {
    summary: 'Restore a database from a backup',
    tag: 'backups',
    floor: 'admin',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/databases/:id/backups/drill': {
    summary: 'Run a restore drill of a backup into a scratch container',
    tag: 'backups',
    floor: 'member',
    bodyType: '{ backupId?: number }',
    responseType: 'BackupDrillResult',
    validation: 'handler',
  },
  'GET /v1/databases/:id/drills': {
    summary: "A database's restore drill history",
    tag: 'backups',
    floor: 'viewer',
    responseType: 'BackupDrillEntry[]',
  },
  'GET /v1/databases/:id/backup-policy': {
    summary: "A database's backup schedule, retention and destination",
    tag: 'backups',
    floor: 'viewer',
    responseType: 'BackupPolicy',
    mcp: { name: 'get_backup_policy', description: 'Backup schedule, retention count and destination of one managed database.', readOnly: true },
  },
  'PUT /v1/databases/:id/backup-policy': {
    summary: "Set a database's backup policy",
    tag: 'backups',
    floor: 'admin',
    body: backupPolicyInput,
    responseType: 'BackupPolicy',
    validation: 'zod',
  },
  'GET /v1/databases/:id/pgbouncer': {
    summary: 'PgBouncer sidecar status',
    tag: 'databases',
    floor: 'member',
    responseType: 'PgbouncerStatus',
  },
  'POST /v1/databases/:id/pgbouncer/enable': {
    summary: 'Enable the PgBouncer sidecar',
    tag: 'databases',
    floor: 'operator',
    localBody: 'pgbouncer.ts#enableBody',
    responseType: 'PgbouncerStatus',
    validation: 'zod',
  },
  'POST /v1/databases/:id/pgbouncer/disable': {
    summary: 'Disable the PgBouncer sidecar',
    tag: 'databases',
    floor: 'operator',
    responseType: 'PgbouncerStatus',
  },
  'POST /v1/databases/:id/studio': {
    summary: 'Start the database Web Studio',
    tag: 'databases',
    floor: 'operator',
    bodyType: '{ port?: number }',
    responseType: '{ ok: boolean; port: number; url: string }',
    validation: 'handler',
  },
  'DELETE /v1/databases/:id/studio': {
    summary: 'Stop the database Web Studio',
    tag: 'databases',
    floor: 'operator',
  },
  'ALL /v1/databases/:id/studio-proxy': {
    summary: 'Web Studio reverse proxy (studio cookie)',
    tag: 'databases',
    description: 'Every HTTP method is proxied to the loopback studio container. The credential is the operator-minted, path-scoped studio cookie.',
    floor: 'token',
  },
  'ALL /v1/databases/:id/studio-proxy/*': {
    summary: 'Web Studio reverse proxy (studio cookie)',
    tag: 'databases',
    description: 'Every HTTP method is proxied to the loopback studio container. The credential is the operator-minted, path-scoped studio cookie.',
    floor: 'token',
  },
  'GET /v1/databases/:id/public-access': {
    summary: "A database's public access state",
    tag: 'databases',
    floor: 'admin',
    responseType: 'PublicAccessStatus',
  },
  'PUT /v1/databases/:id/public-access': {
    summary: 'Configure public access to a database',
    tag: 'databases',
    floor: 'operator',
    body: publicAccessPut,
    responseType: 'PublicAccessStatus',
    validation: 'zod',
  },
  'DELETE /v1/databases/:id/public-access': {
    summary: 'Turn off public access to a database',
    tag: 'databases',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/databases/:id/imports': {
    summary: "List a database's dump imports",
    tag: 'databases',
    floor: 'admin',
  },
  'POST /v1/databases/:id/imports': {
    summary: 'Start a dump import (upload or S3 object)',
    tag: 'databases',
    description: 'An upload body needs admin on the database; an S3 body is operator only.',
    floor: 'operator',
    body: databaseImportCreate,
    validation: 'zod',
  },
  'GET /v1/databases/:id/imports/:importId': {
    summary: 'Get a dump import',
    tag: 'databases',
    floor: 'admin',
  },
  'DELETE /v1/databases/:id/imports/:importId': {
    summary: 'Cancel a dump import',
    tag: 'databases',
    floor: 'admin',
  },
  'PUT /v1/databases/:id/imports/:importId/chunks/:index': {
    summary: 'Upload one chunk of a dump (octet-stream)',
    tag: 'databases',
    description: 'The request body is the raw chunk (application/octet-stream), not JSON.',
    floor: 'admin',
  },
  'POST /v1/databases/:id/imports/:importId/start': {
    summary: 'Run an uploaded dump import',
    tag: 'databases',
    floor: 'admin',
  },
  'GET /v1/backups': {
    summary: 'Every backup the caller can see',
    tag: 'backups',
    floor: 'authed',
    responseType: 'BackupWithDb[]',
  },
  'DELETE /v1/backups/:bid': {
    summary: 'Delete a backup',
    tag: 'backups',
    floor: 'admin',
  },
  'GET /v1/backups/:bid/download': {
    summary: "Download a backup's plaintext dump",
    tag: 'backups',
    floor: 'admin',
    sensitive: true,
  },
  'GET /v1/backup-destinations': {
    summary: 'List backup destinations',
    tag: 'backups',
    floor: 'operator',
  },
  'POST /v1/backup-destinations': {
    summary: 'Create a backup destination',
    tag: 'backups',
    floor: 'operator',
    body: backupDestinationCreate,
    responseType: '{ id: number }',
    validation: 'zod',
  },
  'PATCH /v1/backup-destinations/:id': {
    summary: 'Update a backup destination',
    tag: 'backups',
    floor: 'operator',
    body: backupDestinationPatch,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'DELETE /v1/backup-destinations/:id': {
    summary: 'Delete a backup destination',
    tag: 'backups',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/backup-destinations/:id/test': {
    summary: "Test a backup destination's credentials",
    tag: 'backups',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/backup-destinations/:id/objects': {
    summary: 'List objects in a backup destination',
    tag: 'backups',
    floor: 'operator',
    query: backupDestinationObjectsQuery,
    validation: 'zod',
  },
};
