import {
  containerFileWrite,
  containerPathCreate,
  createTunnel,
  createVolumeBackup,
  serverAnnounce,
  serverCreate,
  serverSshBootstrap,
  serverListItem,
  serverSshTest,
  volumeFileWrite,
  volumePathCreate,
} from '@ninedeploy/schemas';
import { z } from 'zod';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: infrastructure (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const infrastructureSpecs: RouteSpecMap = {
  'GET /v1/servers': {
    summary: 'List server nodes',
    tag: 'servers',
    description:
      'Never the agent token. Additive fields, absent on older panels: `terminal` (0.15), the agent capability cache (`agent`) and what the node can do (`features`, with the update-the-agent `reason`), the build-server role, the hosted database count and the Swarm membership recorded on join (`swarmNodeId`, `swarmRole`).',
    floor: 'operator',
    response: z.array(serverListItem),
    mcp: {
      name: 'list_servers',
      description: 'Registered server nodes: host, port, online status, agent version and features, build-server role, hosted databases and Swarm membership. Operator only.',
      readOnly: true,
    },
  },
  'POST /v1/servers': {
    summary: 'Add a server node',
    tag: 'servers',
    floor: 'operator',
    body: serverCreate,
    validation: 'zod',
  },
  'DELETE /v1/servers/:id': {
    summary: 'Remove a server node',
    tag: 'servers',
    floor: 'operator',
    queryType: '{ force?: string }',
    validation: 'handler',
  },
  'POST /v1/servers/:id/approve': {
    summary: 'Approve a pending server node',
    tag: 'servers',
    floor: 'operator',
    responseType: '{ ok: boolean; status: string }',
  },
  'POST /v1/servers/:id/reject': {
    summary: 'Reject a pending server node',
    tag: 'servers',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/servers/:id/test': {
    summary: "Probe a server node's connectivity",
    tag: 'servers',
    floor: 'operator',
    responseType: '{ ok: boolean; status: string }',
  },
  'GET /v1/servers/:id/stats': {
    summary: 'Live telemetry of a server node',
    tag: 'servers',
    floor: 'operator',
  },
  'GET /v1/servers/:id/bootstrap-logs': {
    summary: 'SSH bootstrap logs of a server node',
    tag: 'servers',
    floor: 'operator',
    responseType: '{ logs: string[] }',
  },
  'POST /v1/servers/ssh-bootstrap': {
    summary: 'Bootstrap a server node over SSH',
    tag: 'servers',
    floor: 'operator',
    body: serverSshBootstrap,
    responseType: 'ServerBootstrapResult',
    validation: 'zod',
  },
  'POST /v1/servers/ssh-test': {
    summary: 'Test an SSH connection before bootstrapping',
    tag: 'servers',
    floor: 'operator',
    body: serverSshTest,
    responseType: 'ServerSshTestResult',
    validation: 'zod',
  },
  'POST /v1/servers/announce': {
    summary: 'Agent self-registration (enrolment token)',
    tag: 'servers',
    floor: 'token',
    body: serverAnnounce,
    validation: 'zod',
  },
  'GET /v1/tunnels': {
    summary: 'List tunnels',
    tag: 'tunnels',
    floor: 'operator',
    responseType: 'TunnelEntry[]',
  },
  'POST /v1/tunnels': {
    summary: 'Create a tunnel',
    tag: 'tunnels',
    floor: 'operator',
    body: createTunnel,
    responseType: 'TunnelEntry',
    validation: 'zod',
  },
  'DELETE /v1/tunnels/:id': {
    summary: 'Delete a tunnel',
    tag: 'tunnels',
    floor: 'operator',
  },
  'GET /v1/networks': {
    summary: 'List Docker networks with their members',
    tag: 'networks',
    floor: 'operator',
    queryType: '{ serverId?: string }',
    validation: 'handler',
    mcp: { name: 'list_networks', description: 'User-defined Docker networks and their member containers. Operator only.', readOnly: true },
  },
  'POST /v1/networks': {
    summary: 'Create a Docker network',
    tag: 'networks',
    floor: 'operator',
    localBody: 'networks.ts#createBody',
    responseType: '{ ok: boolean; name: string }',
    validation: 'zod',
  },
  'DELETE /v1/networks/:name': {
    summary: 'Delete a Docker network',
    tag: 'networks',
    floor: 'operator',
    queryType: '{ serverId?: string }',
    validation: 'handler',
  },
  'GET /v1/networks/:name/members': {
    summary: "List a network's members",
    tag: 'networks',
    floor: 'operator',
    responseType: '{ members: string[] }',
  },
  'POST /v1/networks/attach': {
    summary: 'Attach a container to a network',
    tag: 'networks',
    floor: 'operator',
    localBody: 'networks.ts#attachBody',
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'POST /v1/networks/detach': {
    summary: 'Detach a container from a network',
    tag: 'networks',
    floor: 'operator',
    localBody: 'networks.ts#attachBody',
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'GET /v1/volumes': {
    summary: 'List Docker volumes',
    tag: 'volumes',
    floor: 'operator',
    responseType: 'VolumeEntry[]',
    mcp: { name: 'list_volumes', description: 'Docker volumes on the instance with size and owning service. Operator only.', readOnly: true },
  },
  'POST /v1/volumes/prune': {
    summary: 'Delete every unattached volume',
    tag: 'volumes',
    floor: 'operator',
    responseType: '{ ok: boolean; deleted: number; freedBytes: number }',
  },
  'DELETE /v1/volumes/:name': {
    summary: 'Delete a retained volume',
    tag: 'volumes',
    floor: 'operator',
    queryType: '{ serverId?: string }',
    validation: 'handler',
  },
  'GET /v1/volumes/:name/backups': {
    summary: "List a volume's backups",
    tag: 'volumes',
    floor: 'viewer',
    responseType: 'Backup[]',
  },
  'POST /v1/volumes/:name/backups': {
    summary: 'Back up a volume now',
    tag: 'volumes',
    floor: 'operator',
    body: createVolumeBackup,
    responseType: 'Backup',
    validation: 'zod',
  },
  'POST /v1/volumes/:name/backups/:bid/restore': {
    summary: 'Restore a volume backup',
    tag: 'volumes',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/volumes/:name/backups/:bid/download': {
    summary: 'Download a volume backup',
    tag: 'volumes',
    floor: 'operator',
    sensitive: true,
  },
  'GET /v1/volumes/:name/files': {
    summary: 'List a directory in a volume',
    tag: 'volumes',
    floor: 'operator',
    queryType: '{ path?: string }',
    responseType: '{ path: string; entries: VolumeFileEntry[] }',
    validation: 'handler',
  },
  'GET /v1/volumes/:name/files/content': {
    summary: 'Read a file in a volume (base64)',
    tag: 'volumes',
    floor: 'operator',
    queryType: '{ path?: string }',
    responseType: "{ content: string; encoding: 'utf8' | 'base64' }",
    validation: 'handler',
    sensitive: true,
  },
  'PUT /v1/volumes/:name/files': {
    summary: 'Write a file in a volume (base64)',
    tag: 'volumes',
    floor: 'operator',
    body: volumeFileWrite,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'POST /v1/volumes/:name/files/dir': {
    summary: 'Create a directory in a volume',
    tag: 'volumes',
    floor: 'operator',
    body: volumePathCreate,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'DELETE /v1/volumes/:name/files': {
    summary: 'Delete a file or directory in a volume',
    tag: 'volumes',
    floor: 'operator',
    queryType: '{ path?: string }',
    validation: 'handler',
  },
  'GET /v1/containers/:container/inspect': {
    summary: 'Inspect a container',
    tag: 'containers',
    floor: 'operator',
    responseType: 'ContainerInspectData',
  },
  'GET /v1/containers/:container/compose': {
    summary: 'Generated compose YAML of a container',
    tag: 'containers',
    floor: 'operator',
    responseType: 'ContainerComposeData',
  },
  'GET /v1/containers/:container/files': {
    summary: 'List a directory in a container',
    tag: 'containers',
    floor: 'operator',
    queryType: '{ path?: string }',
    responseType: '{ path: string; entries: VolumeFileEntry[] }',
    validation: 'handler',
  },
  'GET /v1/containers/:container/files/content': {
    summary: 'Read a file in a container (base64)',
    tag: 'containers',
    floor: 'operator',
    queryType: '{ path?: string }',
    responseType: "{ content: string; encoding: 'utf8' | 'base64' }",
    validation: 'handler',
    sensitive: true,
  },
  'PUT /v1/containers/:container/files': {
    summary: 'Write a file in a container (base64)',
    tag: 'containers',
    floor: 'operator',
    body: containerFileWrite,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'POST /v1/containers/:container/files/dir': {
    summary: 'Create a directory in a container',
    tag: 'containers',
    floor: 'operator',
    body: containerPathCreate,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'DELETE /v1/containers/:container/files': {
    summary: 'Delete a file or directory in a container',
    tag: 'containers',
    floor: 'operator',
    queryType: '{ path?: string }',
    validation: 'handler',
  },
  'GET /v1/firewall': {
    summary: 'Firewall status and rules',
    tag: 'firewall',
    floor: 'operator',
  },
  'POST /v1/firewall/recommended': {
    summary: 'Apply the recommended firewall rules',
    tag: 'firewall',
    floor: 'operator',
  },
  'POST /v1/firewall/rules': {
    summary: 'Add a firewall rule',
    tag: 'firewall',
    floor: 'operator',
    localBody: 'firewall.ts#ruleSchema',
    validation: 'zod',
  },
  'DELETE /v1/firewall/rules/:id': {
    summary: 'Delete a firewall rule',
    tag: 'firewall',
    floor: 'operator',
  },
  'POST /v1/firewall/toggle': {
    summary: 'Turn the firewall on or off',
    tag: 'firewall',
    floor: 'operator',
    localBody: 'firewall.ts#toggleSchema',
    validation: 'zod',
  },
  'GET /v1/egress': {
    summary: 'List per-project egress policies',
    tag: 'egress',
    floor: 'operator',
  },
  'POST /v1/egress': {
    summary: "Set a project's egress policy",
    tag: 'egress',
    floor: 'operator',
    bodyType: '{ projectId: number; ip: string; driver?: string; sourceCidr?: string }',
    validation: 'handler',
  },
  'DELETE /v1/egress/:projectId': {
    summary: "Remove a project's egress policy",
    tag: 'egress',
    floor: 'operator',
    queryType: '{ driver?: string }',
    validation: 'handler',
  },
  'GET /v1/orchestrators': {
    summary: 'List detected orchestrators',
    tag: 'orchestrators',
    floor: 'operator',
  },
  'GET /v1/orchestrators/:name/stacks': {
    summary: "List an orchestrator's stacks",
    tag: 'orchestrators',
    floor: 'operator',
    responseType: '{ stacks: Array<{ name: string; serviceCount: number }>; }',
  },
  'GET /v1/orchestrators/:name/stacks/:stack': {
    summary: 'Get one orchestrator stack',
    tag: 'orchestrators',
    floor: 'operator',
  },
};
