import {
  autoPruneConfigUpdate,
  doctorFixRequest,
  logDrainCreate,
  logDrainUpdate,
  panelBackupRestore,
  panelBackupSettingsPatch,
  selfUpdateStart,
} from '@ninedeploy/schemas';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: operations (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const operationsSpecs: RouteSpecMap = {
  'GET /v1/system/resources': {
    summary: 'Host resource usage',
    tag: 'system',
    floor: 'operator',
    responseType: 'DockerResources',
  },
  'GET /v1/system/docker-events': {
    summary: 'Recent Docker events',
    tag: 'system',
    floor: 'operator',
    queryType: '{ minutes?: string }',
    responseType: '{ events: Array<{ time: string; type: string; action: string; name: string }> }',
    validation: 'handler',
  },
  'GET /v1/system/export': {
    summary: 'Download a full system archive',
    tag: 'system',
    floor: 'operator',
    sensitive: true,
  },
  'POST /v1/system/import': {
    summary: 'Restore a full system archive',
    tag: 'system',
    floor: 'operator',
  },
  'POST /v1/system/prune-images': {
    summary: 'Prune unused images',
    tag: 'system',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/system/update-check': {
    summary: 'Check for a newer release',
    tag: 'system',
    floor: 'operator',
    queryType: '{ force?: string }',
    validation: 'handler',
  },
  'POST /v1/system/update-start': {
    summary: 'Start a panel self-update to an exact tag',
    tag: 'system',
    floor: 'operator',
    body: selfUpdateStart,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'GET /v1/system/update-status': {
    summary: 'Panel self-update status',
    tag: 'system',
    floor: 'operator',
    responseType: 'SelfUpdateStatus',
  },
  'GET /v1/system/panel-backup': {
    summary: 'Panel backup settings and last outcome',
    tag: 'system',
    floor: 'operator',
    responseType: 'PanelBackupStatus',
  },
  'PUT /v1/system/panel-backup': {
    summary: 'Set panel backup settings',
    tag: 'system',
    floor: 'operator',
    body: panelBackupSettingsPatch,
    responseType: 'PanelBackupStatus',
    validation: 'zod',
  },
  'POST /v1/system/panel-backup/run': {
    summary: 'Back up the panel now',
    tag: 'system',
    floor: 'operator',
    responseType: '{ ok: boolean; started: boolean }',
  },
  'GET /v1/system/panel-backup/remote': {
    summary: 'List panel backups in a destination',
    tag: 'system',
    floor: 'operator',
    localQuery: 'panelBackup.ts#listQuery',
    validation: 'zod',
    sensitive: true,
  },
  'POST /v1/system/panel-backup/restore': {
    summary: 'Restore the panel from a backup',
    tag: 'system',
    floor: 'operator',
    body: panelBackupRestore,
    responseType: '{ ok: boolean; message: string; meta: unknown; backupPath: string }',
    validation: 'zod',
  },
  'GET /v1/housekeeping/images': {
    summary: 'List images on the host',
    tag: 'housekeeping',
    floor: 'operator',
    responseType: '{ images: ImageInfo[]; totalCount: number; totalBytes: number }',
  },
  'POST /v1/housekeeping/images/prune': {
    summary: 'Prune images',
    tag: 'housekeeping',
    floor: 'operator',
    localBody: 'images.ts#pruneBody',
    responseType: 'PruneImagesResult',
    validation: 'zod',
  },
  'POST /v1/housekeeping/prune': {
    summary: 'Run the housekeeping prune now',
    tag: 'housekeeping',
    floor: 'operator',
    responseType: 'AutoPruneRunResult',
  },
  'GET /v1/housekeeping/prune/config': {
    summary: 'Disk usage and auto-prune settings',
    tag: 'housekeeping',
    floor: 'operator',
    responseType: 'AutoPruneStatus',
  },
  'PATCH /v1/housekeeping/prune/config': {
    summary: 'Update auto-prune settings',
    tag: 'housekeeping',
    floor: 'operator',
    body: autoPruneConfigUpdate,
    responseType: 'AutoPruneStatus',
    validation: 'zod',
  },
  'GET /v1/doctor': {
    summary: 'Scan the host for problems',
    tag: 'doctor',
    floor: 'operator',
    responseType: 'DoctorReport',
    mcp: { name: 'doctor_report', description: 'Host health scan: dead containers, orphan volumes and networks, record/runtime drift, dangling images and disk pressure, each with its suggested repair. Read-only; repairs are not exposed. Operator only.', readOnly: true },
  },
  'POST /v1/doctor/fix': {
    summary: 'Repair one doctor finding',
    tag: 'doctor',
    floor: 'operator',
    body: doctorFixRequest,
    responseType: 'DoctorFixResponse',
    validation: 'zod',
  },
  'GET /v1/metric-history': {
    summary: 'Metric history retention settings',
    tag: 'metrics',
    floor: 'authed',
  },
  'POST /v1/metric-history/flush': {
    summary: 'Run the metric retention sweep now',
    tag: 'metrics',
    floor: 'operator',
    responseType: "{ ok: boolean; backend: 'builtin'; deleted: number }",
  },
  'GET /v1/stats': {
    summary: 'Live host and container resource snapshot',
    tag: 'metrics',
    floor: 'authed',
    responseType: 'StatsSnapshot',
  },
  'GET /v1/dashboard': {
    summary: 'Dashboard overview',
    tag: 'metrics',
    floor: 'authed',
  },
  'GET /v1/topology': {
    summary: 'Domains, services and databases routing graph',
    tag: 'topology',
    floor: 'authed',
    responseType: 'TopologyGraph',
  },
  'GET /v1/activity': {
    summary: 'Audit activity log',
    tag: 'activity',
    floor: 'operator',
    localQuery: 'activity.ts#listQuery',
    validation: 'zod',
  },
  'GET /v1/log-drains': {
    summary: 'List log drains',
    tag: 'log-drains',
    floor: 'operator',
    queryType: '{ serviceId?: string }',
    responseType: 'LogDrain[]',
    validation: 'handler',
  },
  'POST /v1/log-drains': {
    summary: 'Create a log drain',
    tag: 'log-drains',
    floor: 'operator',
    body: logDrainCreate,
    responseType: 'LogDrain',
    validation: 'zod',
  },
  'GET /v1/log-drains/:id': {
    summary: 'Get a log drain',
    tag: 'log-drains',
    floor: 'operator',
    responseType: 'LogDrain',
  },
  'PATCH /v1/log-drains/:id': {
    summary: 'Update a log drain',
    tag: 'log-drains',
    floor: 'operator',
    body: logDrainUpdate,
    responseType: 'LogDrain',
    validation: 'zod',
  },
  'DELETE /v1/log-drains/:id': {
    summary: 'Delete a log drain',
    tag: 'log-drains',
    floor: 'operator',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/log-drains/:id/test': {
    summary: 'Test a log drain',
    tag: 'log-drains',
    floor: 'operator',
    responseType: 'LogDrainTestResult',
  },
  'POST /v1/log-drains/search': {
    summary: 'Search shipped logs (Loki)',
    tag: 'log-drains',
    floor: 'member',
    localBody: 'logSearch.ts#searchBody',
    responseType: 'LogSearchResult',
    validation: 'zod',
  },
  'POST /v1/demo/seed': {
    summary: 'Create the demo service',
    tag: 'demo',
    floor: 'operator',
    responseType: 'DemoSeedResult',
  },
};
