import {
  composePreviewRequest,
  createAttachment,
  createService,
  createServiceVolumeAttachment,
  metricQuery,
  serviceGithubFeedbackPatch,
  serviceGithubLinkPut,
  serviceGithubMigrate,
  setLimits,
  setServiceTags,
  updateService,
  updateServiceVolumeAttachment,
} from '@ninedeploy/schemas';
import { z } from 'zod';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: services (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const servicesSpecs: RouteSpecMap = {
  'GET /v1/services': {
    summary: 'List services',
    tag: 'services',
    floor: 'authed',
    queryType: '{ tagProjectIds?: string; tagWorkspaceIds?: string; tagLabelIds?: string; environmentId?: string }',
    validation: 'handler',
  },
  'POST /v1/services': {
    summary: 'Create a service',
    tag: 'services',
    floor: 'member',
    body: createService,
    responseType: 'Service',
    validation: 'zod',
  },
  'GET /v1/services/:id': {
    summary: 'Get a service',
    tag: 'services',
    floor: 'viewer',
    responseType: 'Service',
  },
  'PATCH /v1/services/:id': {
    summary: 'Update a service',
    tag: 'services',
    floor: 'member',
    body: updateService,
    responseType: 'Service',
    validation: 'zod',
  },
  'DELETE /v1/services/:id': {
    summary: 'Delete a service',
    tag: 'services',
    floor: 'admin',
  },
  'POST /v1/services/:id/clone': {
    summary: 'Clone a service',
    tag: 'services',
    floor: 'admin',
    bodyType: '{ name?: string; slug?: string }',
    responseType: 'Service',
    validation: 'handler',
  },
  'GET /v1/services/:id/export': {
    summary: 'Export a service as a JSON bundle',
    tag: 'services',
    floor: 'operator',
  },
  'POST /v1/services/import': {
    summary: 'Recreate a service from a JSON bundle',
    tag: 'services',
    description: 'Operator only. The body is a service bundle from GET /v1/services/{id}/export.',
    floor: 'operator',
    bodyType: 'ServiceBundle',
    responseType: '{ ok: boolean; serviceId: number; slug: string; message: string }',
    validation: 'handler',
  },
  'POST /v1/services/compose/preview': {
    summary: 'Dry-run a compose file (nothing is written)',
    tag: 'services',
    floor: 'operator',
    body: composePreviewRequest,
    responseType: 'ComposePreviewResponse',
    validation: 'zod',
  },
  'PATCH /v1/services/:id/limits': {
    summary: "Set a service's resource limits",
    tag: 'services',
    floor: 'member',
    body: setLimits,
    responseType: '{ cpuShares: number; cpuLimitMilli: number; memLimitMb: number; liveApplied: boolean }',
    validation: 'zod',
  },
  'POST /v1/services/:id/start': {
    summary: 'Start a service',
    tag: 'services',
    floor: 'member',
    responseType: '{ ok: boolean; status: string }',
  },
  'POST /v1/services/:id/stop': {
    summary: 'Stop a service',
    tag: 'services',
    floor: 'member',
    responseType: '{ ok: boolean; status: string }',
  },
  'POST /v1/services/:id/restart': {
    summary: 'Restart a service',
    tag: 'services',
    floor: 'member',
    responseType: '{ ok: boolean; status: string }',
  },
  'GET /v1/services/:id/logs': {
    summary: 'Recent runtime logs of a service',
    tag: 'services',
    floor: 'viewer',
    responseType: '{ lines: string }',
  },
  'GET /v1/services/:id/metrics': {
    summary: 'CPU and memory history of a service',
    tag: 'services',
    floor: 'viewer',
    query: metricQuery,
    validation: 'zod',
  },
  'POST /v1/services/:id/sticky-session': {
    summary: 'Turn sticky sessions on or off for a service',
    tag: 'services',
    floor: 'admin',
    body: z.object({ enabled: z.boolean() }),
    responseType: '{ id: number; enabled: boolean; active: boolean }',
    validation: 'zod',
  },
  'GET /v1/services/:id/tags': {
    summary: "A service's workspace, project and label tags",
    tag: 'services',
    floor: 'viewer',
    responseType: 'ServiceTags',
  },
  'PUT /v1/services/:id/tags': {
    summary: "Replace a service's tags",
    tag: 'services',
    floor: 'admin',
    body: setServiceTags,
    responseType: 'ServiceTags',
    validation: 'zod',
  },
  'GET /v1/services/:id/targets': {
    summary: "A service's fan-out server targets",
    tag: 'services',
    floor: 'viewer',
    responseType: '{ targets: Array<{ serverId: number; runtimeId: string | null; status: string }> }',
  },
  'PATCH /v1/services/:id/targets': {
    summary: "Set a service's fan-out server targets",
    tag: 'services',
    floor: 'operator',
    localBody: 'services.ts#setTargets',
    responseType: '{ targets: Array<{ serverId: number; runtimeId: string | null; status: string }> }',
    validation: 'zod',
  },
  'POST /v1/services/:id/manifest/apply': {
    summary: 'Apply a .ninedeploy manifest to a service',
    tag: 'services',
    floor: 'operator',
    localBody: 'manifest.ts#applyBody',
    responseType: 'ApplyManifestResult',
    validation: 'zod',
  },
  'GET /v1/services/:id/insights': {
    summary: 'Repository insights for a service',
    tag: 'insights',
    floor: 'viewer',
    responseType: 'RepoInsights | null',
  },
  'POST /v1/services/:id/insights/refresh': {
    summary: "Re-analyse a service's repository",
    tag: 'insights',
    floor: 'member',
    responseType: 'RepoInsights',
  },
  'GET /v1/services/:id/volumes': {
    summary: "List a service's volume attachments",
    tag: 'volumes',
    floor: 'viewer',
    responseType: 'Array<ServiceVolumeAttachment & { sizeBytes: number; inUse: boolean; sharedWith: number }>',
  },
  'POST /v1/services/:id/volumes': {
    summary: 'Attach (or create and attach) a volume',
    tag: 'volumes',
    floor: 'member',
    body: createServiceVolumeAttachment,
    responseType: '{ attachment: ServiceVolumeAttachment; deploymentId: number }',
    validation: 'zod',
  },
  'PATCH /v1/services/:id/volumes/:attId': {
    summary: "Change a volume attachment's path or read-only flag",
    tag: 'volumes',
    floor: 'member',
    body: updateServiceVolumeAttachment,
    responseType: '{ attachment: ServiceVolumeAttachment; deploymentId: number }',
    validation: 'zod',
  },
  'DELETE /v1/services/:id/volumes/:attId': {
    summary: 'Detach a volume (the volume survives)',
    tag: 'volumes',
    floor: 'admin',
  },
  'POST /v1/services/:id/volumes/config-repair': {
    summary: 'Repair a configuration file on an attached volume',
    tag: 'volumes',
    floor: 'member',
    localBody: 'serviceVolumes.ts#repairConfig',
    responseType: '{ ok: boolean; deploymentId: number }',
    validation: 'zod',
  },
  'GET /v1/services/:id/attachments': {
    summary: "List a service's database attachments",
    tag: 'databases',
    floor: 'viewer',
    responseType: 'Attachment[]',
  },
  'POST /v1/services/:id/attachments': {
    summary: 'Attach a database to a service',
    tag: 'databases',
    floor: 'admin',
    body: createAttachment,
    responseType: 'Attachment',
    validation: 'zod',
  },
  'DELETE /v1/services/:id/attachments/:attId': {
    summary: 'Detach a database from a service',
    tag: 'databases',
    floor: 'member',
  },
  'GET /v1/services/:id/github': {
    summary: "A service's GitHub App link",
    tag: 'github',
    floor: 'viewer',
    responseType: 'ServiceGithubStatus',
  },
  'PUT /v1/services/:id/github': {
    summary: 'Link a service to a GitHub App installation',
    tag: 'github',
    floor: 'operator',
    body: serviceGithubLinkPut,
    responseType: '{ link: ServiceGithubLink }',
    validation: 'zod',
  },
  'PATCH /v1/services/:id/github/feedback': {
    summary: 'Toggle GitHub deploy feedback for a service',
    tag: 'github',
    floor: 'admin',
    body: serviceGithubFeedbackPatch,
    responseType: '{ link: ServiceGithubLink }',
    validation: 'zod',
  },
  'POST /v1/services/:id/github/migrate': {
    summary: 'Move a PAT or webhook service onto the GitHub App',
    tag: 'github',
    floor: 'operator',
    body: serviceGithubMigrate,
    responseType: '{ link: ServiceGithubLink }',
    validation: 'zod',
  },
  'POST /v1/services/:id/github/finalize': {
    summary: 'Make a GitHub App migration permanent',
    tag: 'github',
    floor: 'operator',
    responseType: '{ link: ServiceGithubLink; webhooksDeactivated: number }',
  },
  'DELETE /v1/services/:id/github': {
    summary: "Revert a service's GitHub App link",
    tag: 'github',
    floor: 'operator',
    responseType: '{ ok: boolean; sourceId: number | null; webhooksReactivated: number }',
  },
};
