import {
  awsProviderPut,
  createSource,
  githubAppCreate,
  githubAppManifestComplete,
  githubAppManifestRequest,
  githubAppPatch,
  githubAppPrivateKey,
  secretProviderTestRequest,
  setConfigSchema,
  sourcePatch,
  vaultProviderPut,
} from '@ninedeploy/schemas';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: settings (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const settingsSpecs: RouteSpecMap = {
  'GET /v1/settings': {
    summary: 'Instance settings',
    tag: 'settings',
    floor: 'operator',
  },
  'PUT /v1/settings/acme-email': {
    summary: 'Set the ACME email (turns on TLS)',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#emailPatch',
    responseType: '{ ok: boolean; acmeEmail: string | null; applied: string }',
    validation: 'zod',
  },
  'PUT /v1/settings/allow-registration': {
    summary: 'Turn open registration on or off',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#togglePatch',
    responseType: '{ ok: boolean; allowRegistration: boolean }',
    validation: 'zod',
  },
  'PUT /v1/settings/dns': {
    summary: 'Set the DNS challenge provider',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#dnsPatch',
    responseType: '{ ok: boolean; dnsProvider: string | null; wildcardApex: string | null; applied: string }',
    validation: 'zod',
  },
  'GET /v1/settings/dns-records': {
    summary: 'Cloudflare DNS record automation settings',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ enabled: boolean; hasToken: boolean; content: string | null }',
  },
  'PUT /v1/settings/dns-records': {
    summary: 'Set Cloudflare DNS record automation',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#dnsRecordsPatch',
    responseType: '{ ok: boolean; enabled: boolean }',
    validation: 'zod',
  },
  'GET /v1/settings/dns-records/namecheap': {
    summary: 'Namecheap DNS record automation settings',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ configured: boolean; apiUser: string | null; clientIp: string | null; hasKey: boolean }',
  },
  'PUT /v1/settings/dns-records/namecheap': {
    summary: 'Set Namecheap DNS record automation',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#namecheapConfigPatch',
    responseType: '{ ok: boolean; apiUser: string }',
    validation: 'zod',
  },
  'POST /v1/settings/dns-records/test': {
    summary: 'Test the DNS record provider credentials',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ ok: boolean; status?: string; error?: string }',
  },
  'GET /v1/settings/domain-policy': {
    summary: 'Domain-claim limits',
    tag: 'settings',
    floor: 'operator',
  },
  'PUT /v1/settings/domain-policy': {
    summary: 'Set domain-claim limits',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#domainPolicyPatch',
    validation: 'zod',
  },
  'GET /v1/settings/enrolment': {
    summary: 'Node enrolment token status',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ enabled: boolean; token: string | null }',
    sensitive: true,
  },
  'POST /v1/settings/enrolment/rotate': {
    summary: 'Rotate the node enrolment token',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ ok: boolean; enabled: boolean; token: string }',
    sensitive: true,
  },
  'DELETE /v1/settings/enrolment': {
    summary: 'Turn off node enrolment',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ ok: boolean; enabled: boolean }',
  },
  'GET /v1/settings/master-key': {
    summary: 'Master key status',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ activeVersion: number; knownVersions: number[]; rotatable: boolean }',
  },
  'POST /v1/settings/master-key/rotate': {
    summary: 'Rotate the master key and re-encrypt every secret',
    tag: 'settings',
    floor: 'operator',
  },
  'PUT /v1/settings/panel-domain': {
    summary: 'Set the panel domain',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#domainPatch',
    responseType: '{ ok: boolean; panelDomain: string | null }',
    validation: 'zod',
  },
  'PUT /v1/settings/templates-source': {
    summary: 'Set the templates source',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#sourcePatch',
    responseType: '{ ok: boolean; templatesSource: string | null }',
    validation: 'zod',
  },
  'GET /v1/settings/vault': {
    summary: 'Vault integration settings',
    tag: 'settings',
    floor: 'operator',
    responseType: 'VaultSettings',
  },
  'PUT /v1/settings/vault': {
    summary: 'Set the Vault integration',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#vaultPatch',
    responseType: '{ ok: boolean; provider: string | null }',
    validation: 'zod',
  },
  'PUT /v1/settings/vault/allowlist': {
    summary: 'Set the Vault path allow-list',
    tag: 'settings',
    floor: 'operator',
    localBody: 'settings.ts#vaultAllowlistPatch',
    responseType: '{ ok: boolean } & VaultAllowlistView',
    validation: 'zod',
  },
  'POST /v1/settings/vault/test': {
    summary: 'Test the Vault integration',
    tag: 'settings',
    floor: 'operator',
    responseType: '{ ok: boolean; secrets: number }',
  },
  'GET /v1/settings/secret-providers': {
    summary: 'External secret providers',
    tag: 'settings',
    floor: 'operator',
    responseType: 'SecretProviderView[]',
  },
  'PUT /v1/settings/secret-providers/vault': {
    summary: 'Configure the Vault / OpenBao secret provider',
    tag: 'settings',
    floor: 'operator',
    body: vaultProviderPut,
    validation: 'zod',
  },
  'PUT /v1/settings/secret-providers/aws': {
    summary: 'Configure the AWS Secrets Manager provider',
    tag: 'settings',
    floor: 'operator',
    body: awsProviderPut,
    validation: 'zod',
  },
  'DELETE /v1/settings/secret-providers/vault': {
    summary: 'Remove the Vault / OpenBao secret provider',
    tag: 'settings',
    floor: 'operator',
  },
  'DELETE /v1/settings/secret-providers/aws': {
    summary: 'Remove the AWS Secrets Manager provider',
    tag: 'settings',
    floor: 'operator',
  },
  'POST /v1/settings/secret-providers/vault/test': {
    summary: 'Test the Vault / OpenBao secret provider',
    tag: 'settings',
    floor: 'operator',
    body: secretProviderTestRequest,
    validation: 'zod',
  },
  'POST /v1/settings/secret-providers/aws/test': {
    summary: 'Test the AWS Secrets Manager provider',
    tag: 'settings',
    floor: 'operator',
    body: secretProviderTestRequest,
    validation: 'zod',
  },
  'GET /v1/config': {
    summary: 'List configuration entries (secrets masked)',
    tag: 'config',
    floor: 'operator',
    queryType: '{ category?: string; pluginId?: string; reveal?: string }',
    responseType: 'ConfigListResponse',
    validation: 'handler',
    sensitive: true,
  },
  'GET /v1/config/:key': {
    summary: 'Get a configuration entry',
    tag: 'config',
    floor: 'operator',
    queryType: '{ reveal?: string }',
    responseType: 'ConfigItem',
    validation: 'handler',
    sensitive: true,
  },
  'POST /v1/config/:key': {
    summary: 'Set a configuration entry',
    tag: 'config',
    floor: 'operator',
    body: setConfigSchema,
    responseType: '{ ok: boolean; key: string }',
    validation: 'zod',
  },
  'DELETE /v1/config/:key': {
    summary: 'Delete a configuration entry',
    tag: 'config',
    floor: 'operator',
    responseType: '{ ok: boolean; key: string }',
  },
  'GET /v1/config-presets': {
    summary: 'List configuration presets',
    tag: 'config',
    floor: 'operator',
    responseType: '{ presets: string[] }',
  },
  'POST /v1/config-presets': {
    summary: 'Register a configuration preset',
    tag: 'config',
    floor: 'operator',
    localBody: 'configPresets.ts#registerSchema',
    responseType: '{ ok: boolean; id: string; keyCount: number }',
    validation: 'zod',
  },
  'GET /v1/config-presets/:id': {
    summary: 'Get a configuration preset',
    tag: 'config',
    floor: 'operator',
  },
  'DELETE /v1/config-presets/:id': {
    summary: 'Unregister a configuration preset',
    tag: 'config',
    floor: 'operator',
    responseType: '{ ok: boolean; id: string }',
  },
  'PUT /v1/config-presets/:id/apply': {
    summary: 'Apply a configuration preset',
    tag: 'config',
    floor: 'operator',
    localBody: 'configPresets.ts#applyBodySchema',
    validation: 'zod',
  },
  'GET /v1/branding': {
    summary: 'Instance branding',
    tag: 'branding',
    floor: 'authed',
  },
  'PATCH /v1/branding': {
    summary: 'Update instance branding',
    tag: 'branding',
    floor: 'operator',
    bodyType: 'Partial<BrandingStatus>',
    responseType: '{ ok: boolean }',
    validation: 'handler',
  },
  'GET /v1/build-cache/stats': {
    summary: 'Build cache statistics',
    tag: 'build-cache',
    floor: 'authed',
  },
  'POST /v1/build-cache/store': {
    summary: "Record a successful build's digest",
    tag: 'build-cache',
    floor: 'operator',
    bodyType: '{ cacheName?: string; key: string; digest: string; ref?: string; sizeBytes?: number }',
    validation: 'handler',
  },
  'GET /v1/sources': {
    summary: 'List git sources',
    tag: 'sources',
    floor: 'operator',
    responseType: 'Source[]',
  },
  'POST /v1/sources': {
    summary: 'Create a git source',
    tag: 'sources',
    floor: 'operator',
    body: createSource,
    responseType: 'Source',
    validation: 'zod',
  },
  'PATCH /v1/sources/:id': {
    summary: 'Update a git source',
    tag: 'sources',
    floor: 'operator',
    body: sourcePatch,
    responseType: 'Source',
    validation: 'zod',
  },
  'DELETE /v1/sources/:id': {
    summary: 'Delete a git source',
    tag: 'sources',
    floor: 'operator',
  },
  'GET /v1/sources/:id/branches': {
    summary: "List a repository's branches through a source",
    tag: 'sources',
    floor: 'operator',
    queryType: '{ repo?: string }',
    responseType: 'string[]',
    validation: 'handler',
  },
  'GET /v1/sources/:id/repos': {
    summary: 'List repositories a source can reach',
    tag: 'sources',
    floor: 'operator',
  },
  'GET /v1/sources/:id/test': {
    summary: "Test a source's credentials",
    tag: 'sources',
    floor: 'operator',
  },
  'POST /v1/sources/:id/generate-deploy-key': {
    summary: 'Generate an SSH deploy key for a source',
    tag: 'sources',
    floor: 'operator',
    responseType: '{ publicKey: string; fingerprint: string }',
  },
  'POST /v1/github-apps/manifest': {
    summary: 'Start the GitHub App manifest flow',
    tag: 'github-apps',
    floor: 'operator',
    body: githubAppManifestRequest,
    responseType: 'GithubAppManifestResponse',
    validation: 'zod',
  },
  'POST /v1/github-apps/manifest/complete': {
    summary: 'Complete the GitHub App manifest flow',
    tag: 'github-apps',
    floor: 'operator',
    body: githubAppManifestComplete,
    responseType: 'GithubApp',
    validation: 'zod',
  },
  'POST /v1/github-apps': {
    summary: 'Register an existing GitHub App',
    tag: 'github-apps',
    floor: 'operator',
    body: githubAppCreate,
    responseType: 'GithubApp',
    validation: 'zod',
  },
  'GET /v1/github-apps': {
    summary: 'List GitHub Apps',
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubApp[]',
  },
  'GET /v1/github-apps/:id': {
    summary: 'Get a GitHub App',
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubApp',
  },
  'PATCH /v1/github-apps/:id': {
    summary: 'Update a GitHub App',
    tag: 'github-apps',
    floor: 'operator',
    body: githubAppPatch,
    responseType: 'GithubApp',
    validation: 'zod',
  },
  'PUT /v1/github-apps/:id/private-key': {
    summary: "Replace a GitHub App's private key",
    tag: 'github-apps',
    floor: 'operator',
    body: githubAppPrivateKey,
    responseType: 'GithubApp',
    validation: 'zod',
  },
  'POST /v1/github-apps/:id/webhook/sync': {
    summary: "Point a GitHub App's webhook at this panel",
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubApp',
  },
  'POST /v1/github-apps/:id/webhook-secret/rotate': {
    summary: "Rotate a GitHub App's webhook secret",
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubApp',
    sensitive: true,
  },
  'DELETE /v1/github-apps/:id': {
    summary: 'Forget a GitHub App',
    tag: 'github-apps',
    floor: 'operator',
  },
  'POST /v1/github-apps/:id/installations/sync': {
    summary: "Sync a GitHub App's installations",
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubAppInstallationSync',
  },
  'GET /v1/github-apps/:id/installations': {
    summary: "List a GitHub App's installations",
    tag: 'github-apps',
    floor: 'operator',
    responseType: 'GithubAppInstallation[]',
  },
};
