import {
  operatorGrant,
  passwordReset,
  userCreate,
  workspaceCreate,
  workspaceInvitationCreate,
  workspaceMemberAdd,
  workspaceMemberRoleUpdate,
  workspaceUpdate,
} from '@ninedeploy/schemas';
import type { RouteSpecMap } from '../types.js';

/**
 * ROUTE_SPECS fragment: workspaces (routes that predate 0.15). Owner: task T4.
 * Floors mirror the authorization matrix (`test/authzMatrix.test.ts`, which
 * cross-checks every entry); bodies name the zod schema the handler parses.
 */
export const workspacesSpecs: RouteSpecMap = {
  'GET /v1/workspaces': {
    summary: 'List the workspaces the caller belongs to',
    tag: 'workspaces',
    floor: 'authed',
    responseType: 'WorkspaceEntry[]',
  },
  'POST /v1/workspaces': {
    summary: 'Create a workspace',
    tag: 'workspaces',
    floor: 'authed',
    body: workspaceCreate,
    responseType: 'WorkspaceEntry',
    validation: 'zod',
  },
  'GET /v1/workspaces/:id': {
    summary: 'Get a workspace with its members',
    tag: 'workspaces',
    floor: 'viewer',
    responseType: 'WorkspaceDetail',
  },
  'PATCH /v1/workspaces/:id': {
    summary: 'Update a workspace',
    tag: 'workspaces',
    floor: 'admin',
    body: workspaceUpdate,
    responseType: 'WorkspaceEntry',
    validation: 'zod',
  },
  'DELETE /v1/workspaces/:id': {
    summary: 'Delete a workspace',
    tag: 'workspaces',
    floor: 'owner',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/workspaces/:id/invitations': {
    summary: "List a workspace's invitations",
    tag: 'workspaces',
    floor: 'admin',
    responseType: 'WorkspaceInvitationEntry[]',
  },
  'POST /v1/workspaces/:id/invitations': {
    summary: 'Invite someone to a workspace',
    tag: 'workspaces',
    floor: 'admin',
    body: workspaceInvitationCreate,
    responseType: 'WorkspaceInvitationEntry',
    validation: 'zod',
  },
  'DELETE /v1/workspaces/:id/invitations/:inviteId': {
    summary: 'Revoke a pending invitation',
    tag: 'workspaces',
    floor: 'admin',
    responseType: '{ ok: boolean }',
  },
  'POST /v1/workspaces/:id/members': {
    summary: 'Add a member (or invite an unregistered address)',
    tag: 'workspaces',
    floor: 'admin',
    body: workspaceMemberAdd,
    responseType: 'WorkspaceMemberEntry | WorkspaceMemberInviteEntry',
    validation: 'zod',
  },
  'PATCH /v1/workspaces/:id/members/:memberId': {
    summary: "Change a member's role or transfer ownership",
    tag: 'workspaces',
    floor: 'admin',
    body: workspaceMemberRoleUpdate,
    responseType: 'WorkspaceMemberEntry',
    validation: 'zod',
  },
  'DELETE /v1/workspaces/:id/members/:memberId': {
    summary: 'Remove a member (or leave the workspace)',
    tag: 'workspaces',
    floor: 'admin',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/workspaces/:wid/email-templates': {
    summary: "List a workspace's email templates and overrides",
    tag: 'workspaces',
    floor: 'member',
    responseType: '{ workspaceId: number; templates: EmailTemplateEntry[] }',
  },
  'POST /v1/workspaces/:wid/email-templates/preview': {
    summary: 'Render an email template preview',
    tag: 'workspaces',
    floor: 'member',
    localBody: 'emailTemplates.ts#previewBody',
    responseType: 'EmailTemplateRender',
    validation: 'zod',
  },
  'PUT /v1/workspaces/:wid/email-templates/:name': {
    summary: "Set a workspace's email template override",
    tag: 'workspaces',
    floor: 'admin',
    localBody: 'emailTemplates.ts#setBody',
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'DELETE /v1/workspaces/:wid/email-templates/:name': {
    summary: "Reset a workspace's email template override",
    tag: 'workspaces',
    floor: 'admin',
    responseType: '{ ok: boolean }',
  },
  'GET /v1/invitations/:token': {
    summary: 'Preview an invitation by its token',
    tag: 'workspaces',
    floor: 'token',
    responseType: 'WorkspaceInvitationPublic',
  },
  'POST /v1/invitations/:token/accept': {
    summary: 'Accept an invitation as the signed-in user',
    tag: 'workspaces',
    floor: 'token',
    responseType: '{ ok: boolean; workspaceId: number; role: WorkspaceRole }',
  },
  'GET /v1/users': {
    summary: 'List users',
    tag: 'users',
    floor: 'operator',
    responseType: 'PublicUser[]',
  },
  'POST /v1/users': {
    summary: 'Create a user',
    tag: 'users',
    floor: 'operator',
    body: userCreate,
    responseType: 'PublicUser',
    validation: 'zod',
  },
  'DELETE /v1/users/:id': {
    summary: 'Delete a user',
    tag: 'users',
    floor: 'operator',
    bodyType: '{ transferTo?: unknown }',
    queryType: '{ transferTo?: string }',
    validation: 'handler',
  },
  'PATCH /v1/users/:id/operator': {
    summary: 'Grant or revoke the instance-operator flag',
    tag: 'users',
    floor: 'operator',
    body: operatorGrant,
    responseType: '{ ok: boolean; id: number; isOperator: boolean }',
    validation: 'zod',
  },
  'PATCH /v1/users/:id/password': {
    summary: "Set a user's password",
    tag: 'users',
    floor: 'operator',
    body: passwordReset,
    responseType: '{ ok: boolean }',
    validation: 'zod',
  },
  'POST /v1/users/:id/reset-link': {
    summary: 'Issue a one-time password reset link for a user',
    tag: 'users',
    floor: 'operator',
    responseType: '{ url: string; expiresAt: string }',
    sensitive: true,
  },
};
